### ISSUE TITLE
Getting weird extraneous characters in jasperStarter command

### ISSUE THREAD

**Issue by hondaman900** [cossou/JasperPHP#100]
I'm trying to get this working with Laravel 5.5, and feel I'm close, but am experiencing weird stuff.

I have my compiled report file DS_Test.jasper (from JasperStudio) in my Laravel storage\reports folder. The report looks fine in JasperStudio.

I keep getting the error:
`Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.`

I have followed the examples given (and trolled many posts) and can't seem to get this to execute.

Code (using DD to test output. If I use ` ->execute() `at the end it gives the error above):
```
    $jasper = new JasperPHP\JasperPHP;
    $input = storage_path().'\reports\DS_Test.jasper';
    $output = storage_path();
    
    $jasper->process(
        $input,
        $output,
        array("pdf"),
        array(),
        Config::get('database.connections.mysql')
        )->output();
    dd($jasper);
```

DD output gives gives (note all the "^" symbols in paths):
```
JasperPHP {#1233 ▼
  #executable: "/../JasperStarter/bin/jasperstarter"
  #the_command: "C:^\xampp^\htdocs^\DS_dev_01^\vendor^\cossou^\jasperphp^\src^\JasperPHP/../JasperStarter/bin/jasperstarter process C:^\xampp^\htdocs^\DS_dev_01^\storage^\reports^\DS_Test.jasper -o C:^\xampp^\htdocs^\DS_dev_01^\storage -f pdf -r C:^\xampp^\htdocs^\DS_dev_01^\vendor^\cossou^\jasperphp^\src^\JasperPHP/../../../../../ -t mysql -u dstest -p dstest -H 127.0.0.1 -n dstest --db-port 3306 ◀"
  #redirect_output: true
  #background: true
  #windows: true
  #formats: array:13 [▼
    0 => "pdf"
    1 => "rtf"
    2 => "xls"
    3 => "xlsx"
    4 => "docx"
    5 => "odt"
    6 => "ods"
    7 => "pptx"
    8 => "csv"
    9 => "html"
    10 => "xhtml"
    11 => "xml"
    12 => "jrprint"
  ]
  #resource_directory: "C:\xampp\htdocs\DS_dev_01\vendor\cossou\jasperphp\src\JasperPHP/../../../../../"
}
```

if I assign the `$jasper->process... `statement to a variable `$x`, as suggested in another post, and then `echo $x;` to dump that variable, I get even more "^" symbols, as follows:

`C:\xampp\htdocs\DS_dev_01\storageC:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../JasperStarter/bin/jasperstarter process C:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\storage^^^\reports^^^\DS_Test.jasper -o C:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\storage -f pdf -r C:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../../../../../ -t mysql -u dstest -p dstest -H 127.0.0.1 -n dstest --db-port 3306`

Any ideas? All suggestions are most welcome.

**Comment by cossou** [comment]
Hi @hondaman900, 

you should run this on your terminal:

```
C:\xampp\htdocs\DS_dev_01\storageC:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../JasperStarter/bin/jasperstarter process C:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\storage^^^\reports^^^\DS_Test.jasper -o C:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\storage -f pdf -r C:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../../../../../ -t mysql -u dstest -p dstest -H 127.0.0.1 -n dstest --db-port 3306
```

There `^` are added because you are on Windows.

**Comment by hondaman900** [comment]
Hi @Cossou,

Thank you so much for the quick reply.

I had tried that, pasting the string into a terminal window, and the system doesn't like the path, and throws an error:

```
C:\xampp\htdocs\DS_dev_01\storageC:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPH
P/../JasperStarter/bin/jasperstarter : The term 'C:\xampp\htdocs\DS_dev_01\storageC:^^^\xampp^^^\htdocs^^^\DS_dev_01^^^
\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../JasperStarter/bin/jasperstarter' is not recognized as the name
of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1
+ C:\xampp\htdocs\DS_dev_01\storageC:^^^\xampp^^^\htdocs^^^\DS_dev_01^^ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\xampp\htdocs...n/jasperstarter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
If I paste the command string into a text editor and delete all "^" characternand then use it in terminal, I get the same result.

If I manually paste a direct correct path to `jasperstart.exe` like so:

```
C:\xampp\htdocs\DS_dev_01\vendor\cossou\jasperphp\src\JasperStarter\bin\jasperstarter process C:\xampp\htdocs\DS_dev_01\storage\reports
\DS_Test.jasper -o C:\xampp\htdocs\DS_dev_01\storage -f pdf -r C:\xampp\htdocs\DS_dev_01\vendor\cossou\jasperphp\src\JasperPHP/../../../../../ -t mysql -u dstest -p
dstest -H 127.0.0.1 -n dstest --db-port 3306
```

It seems to do something, in that a separate terminal window appears (nothing in it) for a short while, then disappears, and the command prompt returns beneath the command, all as you'd expect would occur while processing the command. However, I can't locate a PDF report anywhere. Feels like I'm close but no output. I'd still need to figure out how in Laravel to have this generate a correct path to the executable and then execute the command to produce the report (and then display that for the user).

Any suggestions as to what to test next?

**Comment by hondaman900** [comment]
So, in Tinker I tried just running the **hello-world** example you provide, just to see if I could get it to function, and then work from there. This is what I get in Tinker:

```
>>> JasperPHP::process(
base_path('/vendor/cossou/jasperphp/examples/hello_world.jasper'),
false,
array('pdf', 'rtf'),
array('php_version' => phpversion())
)->execute();
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/jasperreports/functions/standard/MathFunctions : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:156)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:114)
        at net.sf.jasperreports.functions.FunctionsBundle.addFunctionClass(FunctionsBundle.java:83)
        at net.sf.jasperreports.functions.FunctionsBundle.<init>(FunctionsBundle.java:53)
        at net.sf.jasperreports.functions.FunctionsRegistryFactory.createRegistry(FunctionsRegistryFactory.java:73)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:295)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:270)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:190)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:153)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:125)
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:86)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:111)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:69)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:57)
        at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:219)
        at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:234)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:134)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:667)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:983)
        at de.cenote.jasperstarter.Report.fill(Report.java:237)
        at de.cenote.jasperstarter.App.processReport(App.java:217)
        at de.cenote.jasperstarter.App.main(App.java:102)
Exception with message 'Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.'
```

Looking up this `Unsupported major.minor version 52.0` error would indicate an incompatibility between the JRE used to run the report and the Java version used to compile it. In JasperStudio I changed the Java compile preferences to 1.7 (and also 1.6) but still get the same error.

Does this error dump help point to my issue?

**Comment by cossou** [comment]
Sorry, have no idea why it happens.

**Comment by ruibarbosareb** [comment]
> Então, no Tinker eu tentei apenas executar o exemplo de **hello-world que** você fornece, apenas para ver se eu poderia fazê-lo funcionar, e depois trabalhar a partir daí. Isto é o que eu recebo no Tinker:
> 
> ```
> >>> JasperPHP::process(
> base_path('/vendor/cossou/jasperphp/examples/hello_world.jasper'),
> false,
> array('pdf', 'rtf'),
> array('php_version' => phpversion())
> )->execute();
> Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/jasperreports/functions/standard/MathFunctions : Unsupported major.minor version 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.access$100(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Unknown Source)
>         at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:156)
>         at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:114)
>         at net.sf.jasperreports.functions.FunctionsBundle.addFunctionClass(FunctionsBundle.java:83)
>         at net.sf.jasperreports.functions.FunctionsBundle.<init>(FunctionsBundle.java:53)
>         at net.sf.jasperreports.functions.FunctionsRegistryFactory.createRegistry(FunctionsRegistryFactory.java:73)
>         at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:295)
>         at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:270)
>         at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:190)
>         at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:153)
>         at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:125)
>         at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:86)
>         at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:111)
>         at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:69)
>         at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:57)
>         at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:219)
>         at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:234)
>         at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:134)
>         at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:667)
>         at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:983)
>         at de.cenote.jasperstarter.Report.fill(Report.java:237)
>         at de.cenote.jasperstarter.App.processReport(App.java:217)
>         at de.cenote.jasperstarter.App.main(App.java:102)
> Exception with message 'Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.'
> ```
> 
> Observar esse `Unsupported major.minor version 52.0`erro indicaria uma incompatibilidade entre o JRE usado para executar o relatório e a versão Java usada para compilá-lo. No JasperStudio, alterei as preferências de compilação do Java para 1.7 (e também para o 1.6), mas ainda obtenho o mesmo erro.
> 
> Esse erro despeja o ponto de ajuda para o meu problema?

Managed to solve?
