### ISSUE TITLE
Conexão Json

### ISSUE THREAD

**Issue by fabiolafreitas** [cossou/JasperPHP#104]
Não estou conseguindo fazer a conexão com Json poderia me disponibilizar um exemplo?

**Comment by cossou** [comment]
Olá @fabiolafreitas 

tem algum erro em particular? Há um exemplo no readme.

**Comment by fabiozech** [comment]
Teria como disponibilizar um exemplo de implementação no CodeIgniter, tentei implementar mas sem sucesso.
