### ISSUE TITLE
Implementação

### ISSUE THREAD

**Issue by fabiozech** [cossou/JasperPHP#105]
Teria como disponibilizar um exemplo de implementação no CodeIgniter, tentei implementar mas sem sucesso.

**Comment by umarley** [comment]
Bom dia Fábio!!!

Eu fiz a implementação em Codigniter e funcionou beleza, segue o código abaixo, veja se te ajuda!!!

`private function getConfigDB(){

        include APPPATH . 'config/database.php';

        $dbConfig = [
            'driver' => DRIVER_MYSQL,
            'username' => $db['default']['username'],
            'host' => $db['default']['hostname'],
            'database' => $db['default']['database'],
            'password' => $db['default']['password'],
            'port' => PORTA_MYSQL,
            'jdbc_driver' => APPPATH . 'libraries/JasperPHP/src/JasperStarter/jdbc/mysql-connector-java-5.1.45-bin.jar'
        ];

        return $dbConfig;
    }

    private function getPathJRXML($rowRelatorio){
        $diretorioInput = APPPATH . 'reports';
        $fileJRXML = str_replace("/", DIRECTORY_SEPARATOR, $rowRelatorio->path_jrxml);
        return $diretorioInput . DIRECTORY_SEPARATOR . $fileJRXML;
    }

    private function getDiretorioOutput(){
        $output = APPPATH . 'reports'. DIRECTORY_SEPARATOR .'output';
        return $output;
    }
    
    private function jasper($rowRelatorio, $arParametros = []){
         $arDbConfig = $this->getConfigDB();
         $oJasperPHP = new \JasperPHP\JasperPHP();
        $input = $this->getPathJRXML($rowRelatorio);
        $output = $this->getDiretorioOutput();
        $options = ['pdf'];

       $oJasperPHP->process(
            $input,
            $output,
            $options,
            $arParametros,
            $arDbConfig
        )->execute();
       $fileJRXML = explode("/", $rowRelatorio->path_jrxml);
       $nomeFile = str_replace(['jrxml', 'jasper'], "pdf", $fileJRXML[1]);
       redirect("application/reports/output/{$nomeFile}");
    }`

**Comment by fabiozech** [comment]
Nesse casso você só chama o $this->jasper($rowRelatorio, $arParametros = []) 
Passado o endereço do relatório($rowRelatorio) e os parametros($arParametros)
Certo?

**Comment by umarley** [comment]
Boa noite Fábio!

Veja que eu instancio o objeto.

$oJasperPHP = new \JasperPHP\JasperPHP();

E logo abaixo eu chamo o metodo process e execute:

$oJasperPHP->process(
        $input,
        $output,
        $options,
        $arParametros,
        $arDbConfig
    )->execute();

Quanto ao método jasper esta no controller, esse poderá ser chamado via url. Ele foi desenvolvido de acordo com a estrutura qual tenho aqui. Para exemplo olhe somente o que esta declarado dentro dele.
