### ISSUE TITLE
html tags on parameters

### ISSUE THREAD

**Issue by ccarrionp** [cossou/JasperPHP#106]
$consideracion= "<i>Santiago, 26 de Julio de 2018</i><br><b>De nuestra consideración:</b>";

In generated report dont show cursive and bold text, i check the parameters and markup (set to "html"), when i try the same parameters directly on jasperstudio works fine.

**Comment by cossou** [comment]
Hi @ccarrionp you should probably retrieve that information from the DB. 
The parameters support is limited to primitive types and the encoding can become a problem.
