### ISSUE TITLE
XML data-type

### ISSUE THREAD

**Issue by Lluisma** [cossou/JasperPHP#108]
When trying to generate a report using and .xml file raises this error message:

`jasperstarter: error: argument --xml-xpath is required`

**Comment by Lluisma** [comment]
Adding this lines inside public function **process** in **JasperPHP.php** file solves the problem:

`if ( isset($db_connection['xml_xpath']) && !empty($db_connection['xml_xpath']) )`
`  $command .= ' --xml-xpath ' . $db_connection['xml_xpath'];`

Is this the correct solution or I'm doing something wrong?

**Comment by cossou** [comment]
Hi @Lluisma 

how are you calling the process function? 

I guess the example you mention is correct. 
Maybe we are lacking support for XML.

**Comment by Lluisma** [comment]
Hi, @cossou 

I'm calling the process function this way:

`		// * Genera PDF
		
		$jasper = new JasperPHP;																											// Crea l'objecte JasperPHP
			
		$jasper->process(																											
			$jspr_path,
			$rpt_path,
			array('pdf'),																															// Formats de sortida del report
			array(),							 																										// Paràmetres del report
			array('data_file' => $xml_file, 'driver' => 'xml', 'xml_xpath' => $xml_xpath)
			
		)->execute(); `
