### ISSUE TITLE
how i can preview report page

### ISSUE THREAD

**Issue by mohamed4shim** [cossou/JasperPHP#109]
how i can preview report page which contain print option and next and prev
![image](https://user-images.githubusercontent.com/5725759/51726339-8537dc00-206f-11e9-835b-4d90986898b8.png)

**Comment by mohamed4shim** [comment]
any one can help me view report viewer in web page?

**Comment by cossou** [comment]
Hi @mohamed4shim 

we don't provide a way to display the PDF in a web-page. 
Just a way to generate the PDF. 

Take a look at "PDF.js" or something to show the PDF in the browser.
