### ISSUE TITLE
Problem call JasperPHP

### ISSUE THREAD

**Issue by punnawat** [cossou/JasperPHP#11]
I use Laravel 4.2 and PHP 5.6 on Yosemite.

I create a ReportController, as below

class ReportController extends BaseController {
	public function getTest() {
		JasperPHP::compile(base_path() . '/vendor/cossou/jasperphp/examples/hello_world.jrxml')->execute();
}

I call it by http://localhost/example/report/test ==> return white page and any don't created.

When I manually command at terminal, as below:

/Applications/XAMPP/xamppfiles/htdocs/example/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter cp /Applications/XAMPP/xamppfiles/htdocs/example/vendor/cossou/jasperphp/examples/hello_world.jrxml

--> There is a hello_world.jasper

How to fix it?

PS. php exec() is enable, because " echo exec('pwd') => show the current path correctly "

**Comment by cossou** [comment]
Hi @punnawat first you have to create a .jasper file (it's a .jrxml compiled) with the version 2.0.0 you don't need this anymore. You can directly use the .jrxml.
