### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by prast1007** [cossou/JasperPHP#110]
I got the above error mesage when I tried  to used it with yii2

it refers to line68 at /vendor/cossou/jasperphp/src/JasperPHP/JasperPHP.php

this is my action in the controller

   public function actionTest()
    {
        Yii::setAlias('@report', '@webroot/report');
        // return $this->render('index');
        JasperPHP::process(
            Yii::getAlias('@report') . '/test.jasper', 
            false, 
            array('pdf'), 
            array(
                'id_upk'=> 7, 
                'id_sub_upk' => 1390,
            ),
            array(
                'driver' => 'postgres',
                'username' => 'bapemas',
                'password' => 'bpms;aea',
                'host' => 'db.upk.online',
                'database' => 'db_bapemas',
                'port' => '5433',
            )
        )->execute();
    }

**Comment by cossou** [comment]
Hi @prast1007 did you manage to fix it? 
Can you put the full error output?
