### ISSUE TITLE
Need to use jdbc-dir param

### ISSUE THREAD

**Issue by gianfebrian** [cossou/JasperPHP#12]
I really think it's better to include jdbc-dir param (JasperStarter) in process method.

**Comment by cossou** [comment]
Hi @gianfebrian

Thanks for the PR.
I don't want to bundle all the jars with the repo. The jars should be user responsibility.

What do you think?

**Comment by cossou** [comment]
Hi @gianfebrian we just added version 2.0.0 where you can add the resources directory in the constructor. This will probably meet your requirements

**Comment by gianfebrian** [comment]
I agree with you about the jars and thank you for letting me know about this update. I will update my projects to this version.
