### ISSUE TITLE
JasperPHP and APIs

### ISSUE THREAD

**Issue by julillosamaral** [cossou/JasperPHP#14]
This is not an issue but I don't know where to ask it.

Can we use the jasper report functionality to call an API?

Thanks,
Julio

**Comment by cossou** [comment]
Sorry Julio, can you be more specific?

**Comment by julillosamaral** [comment]
Sure!

I have an REST API which gives me responses that are JSON. I want to call that API from my report and consume the data and with this data fill my report.

Is that ok?

Thanks!

**Comment by cossou** [comment]
You hace to check if Jasper supports that. Never tried that but maybe it will work.
