### ISSUE TITLE
Java 8 and Laravel 5.1

### ISSUE THREAD

**Issue by wmfairuz** [cossou/JasperPHP#16]
WIll it work in Laravel 5.1 and Java 8? 

Thanks

**Comment by cossou** [comment]
Hi @wmfairuz didn't try yet! Feel free to try it and let me know.

**Comment by cossou** [comment]
Hi @wmfairuz we just lunched the v2.0.0 compatible with Java 8.
There is also an example of L5 in the README.
Can you check it?
