### ISSUE TITLE
Report not loading

### ISSUE THREAD

**Issue by JFSolorzano** [cossou/JasperPHP#17]
I followed [this guide](http://codelution.com/development/web/easy-laravel-5-reporting-using-jasper-report/) but i'my having some problems but it just says this:

There was and error executing the report! Time to check the logs!

I'm working with laravel 5.0 and Java 8

**Comment by attrox** [comment]
Instead of the execute() method, run echo $jasper->output(). Try to run the printed output on the command line so you can see a better error message to indicate the problem.

**Comment by cossou** [comment]
@JFSolorzano can you check with the new 2.0.0 version? It's compatible with Java 8. If you still get an error please fill a new issue.
