### ISSUE TITLE
report can loading  in debian server 

### ISSUE THREAD

**Issue by chliguiy** [cossou/JasperPHP#20]
/opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/examples/hello_world.jasper/opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter pr /opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/examples/report1.jrxml -o /opt/lampp/htdocs/laravel/public/report -f pdf rtf -r /opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P php_version=5.5.28 2> /dev/null   && echo ok || echo nook
resultat : nook
problem jasperstarter.exe ????
help me pls

**Comment by cossou** [comment]
Hi @chliguiy 

the first part: `/opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/examples/hello_world.jasper/opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter` 

should be 

`/opt/lampp/htdocs/laravel/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter`

**Comment by chliguiy** [comment]
yes it's output from the program!
i use debian jessie 8.0
Java installed correctly
question::jasper php is working with debian or system unix ??
tnx!!!

**Comment by cossou** [comment]
There are no significant changes in Debian. I use it in Ubuntu (Debian based) and it's working fine.

**Comment by chliguiy** [comment]
do you give me your command? or your test project??
tnx @cossou

**Comment by cossou** [comment]
First of all you need to use the `.jasper` not the `.jrxml`. Edit the `JasperPHP.php` file and capture the `$this->the_command` on line 138.

**Comment by chliguiy** [comment]
i use .jasper  again not working!!!!
i edit japserphp.php
do you give me i test project in my mail:chliguiy@gmail.com
tnx  @cossou

**Comment by cossou** [comment]
Sorry, can not send you the project. You will have to figure it out.

**Comment by chliguiy** [comment]
tnx @cossou   is working in windows but debian not !!
