### ISSUE TITLE
Subreport

### ISSUE THREAD

**Issue by ThiagoHMarques** [cossou/JasperPHP#26]
I'm trying to run a report that has a subreport and is giving error , how should I compile the report ?

**Comment by cossou** [comment]
Do you have the output from the command? Try running the command in the console.

**Comment by ThiagoHMarques** [comment]
It is not finding my subreport, I have to spend the full path him for parameter ?

**Comment by cossou** [comment]
Try that. Never worked with subreports, sorry!

**Comment by jdiefenbach83** [comment]
Hello! I faced this issue! You must set the **resource_dir** before compile.

I created an object from JasperPHP and instanced it. In the constructor parameter, I passed the directory where the main report and subreports were.

PS. My main report call 3 subreports. That way work fine.
