### ISSUE TITLE
JDBC driver

### ISSUE THREAD

**Issue by ThiagoHMarques** [cossou/JasperPHP#27]
Good morning cossou,
it is possible to put the jdbc sql server that comes as part of its component as is done with the mysql and postgres ? I can send the driver right now to be updated component . Thank you very much in advance.

**Comment by cossou** [comment]
Hi Tiago,

you can set your **JDBC driver** manually with the `jdbc_driver` & `jdbc_dir` options:

```php
if( isset($db_connection['jdbc_driver']) && !empty($db_connection['jdbc_driver']) )
                $command .= " --db-driver " . $db_connection['jdbc_driver'];

if ( isset($db_connection['jdbc_dir']) && !empty($db_connection['jdbc_dir']) ) 
                $command .= ' --jdbc-dir ' . $db_connection['jdbc_dir'];
```

And you can place the `.jar` file anywhere in your file system.

Check this documentation: http://jasperstarter.cenote.de/usage.html
