### ISSUE TITLE
Cannot generate PDF, DB problem or what ?

### ISSUE THREAD

**Issue by shresthaankit7** [cossou/JasperPHP#29]
I've been following https://github.com/cossou/JasperPHP and https://gist.github.com/cossou/8369900 tutorials. 

 JasperPHP::compile(storage_path() .'/finalreport.jrxml')->execute();
        JasperPHP::process(
            storage_path().'/finalreport.jrxml', 
            false,
            array("pdf"),
            array("name"=>"ANKIT","address"=>"CHHETRAPTI","country"=>"NEPAL"),
            Config::get('database.connections.mysql')
        )->execute();

This line doesn't do any thing. The output after  exec($this->the_command, $output, $return_var); is 
array(0) { } .. But in termial gives [1] 2225 or something like this output.. 
I am using laravel 4.2 .. I cannot track error nor find solution. Please help

**Comment by shresthaankit7** [comment]
Basically all i am asking is, is there any example to show to display generated PDF which has data from the database rather than only using the phpversion() as of all the examples !!!

**Comment by cossou** [comment]
Hi @shresthaankit7 try:

```
echo JasperPHP::process(
    storage_path().'/finalreport.jrxml', 
    false,
    array("pdf"),
    array("name"=>"ANKIT","address"=>"CHHETRAPTI","country"=>"NEPAL"),
    Config::get('database.connections.mysql')
)->output();
```

**Comment by shresthaankit7** [comment]
Not working.
My .jasper file is shown as:
<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="Myreport" language="groovy" pageWidth="612" pageHeight="792" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="e5347342-85ab-436a-842a-c1c921137732">
	<property name="ireport.zoom" value="1.0"/>
	<property name="ireport.x" value="0"/>
	<property name="ireport.y" value="0"/>
	<queryString>
		<![CDATA[select * from users]]>
	</queryString>
	<field name="id" class="java.lang.Long">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="name" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="address" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="country" class="java.lang.String">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="created_at" class="java.sql.Timestamp">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<field name="updated_at" class="java.sql.Timestamp">
		<fieldDescription><![CDATA[]]></fieldDescription>
	</field>
	<background>
		<band splitType="Stretch"/>
	</background>
	<title>
		<band height="79" splitType="Stretch">
			<staticText>
				<reportElement x="245" y="23" width="100" height="20" uuid="d4bd74b4-218e-4526-b523-8fa0fe7507ac"/>
				<text><![CDATA[MyReport]]></text>
			</staticText>
		</band>
	</title>
	<pageHeader>
		<band height="35" splitType="Stretch"/>
	</pageHeader>
	<columnHeader>
		<band height="61" splitType="Stretch">
			<staticText>
				<reportElement x="295" y="2" width="100" height="20" uuid="776a10bf-6d9f-48b6-9040-360d40a8b1b4"/>
				<text><![CDATA[name]]></text>
			</staticText>
		</band>
	</columnHeader>
	<detail>
		<band height="125" splitType="Stretch">
			<textField>
				<reportElement x="295" y="15" width="100" height="20" uuid="7d943dd0-75b1-4034-9d84-9f7aa87938c8"/>
				<textFieldExpression><![CDATA[$F{name}]]></textFieldExpression>
			</textField>
		</band>
	</detail>
	<columnFooter>
		<band height="45" splitType="Stretch"/>
	</columnFooter>
	<pageFooter>
		<band height="54" splitType="Stretch"/>
	</pageFooter>
	<summary>
		<band height="42" splitType="Stretch"/>
	</summary>
</jasperReport>
