### ISSUE TITLE
Error using database Postgres

### ISSUE THREAD

**Issue by eduavila** [cossou/JasperPHP#31]
This error occurs when using laravel with Postgres database. find that driver laravel. the laravel accepts only "pgsql", but in the parameter is from Jasper to be the drive "postgres".

![screen shot 2016-01-14 at 11 07 59 am](https://cloud.githubusercontent.com/assets/1779843/12326652/ed340608-bab0-11e5-8d6a-3008fd97f58d.png)

**Comment by cossou** [comment]
@eduavila oh. Bummer. 

Can you force the database field to 'postgres'?

**Comment by eduavila** [comment]
Bummer?

Yes. there arises postgres works!

**Comment by cossou** [comment]
Great. I will try to document that in the Readme file.
