### ISSUE TITLE
Error when try to generate pdf report in laravel

### ISSUE THREAD

**Issue by stojankukrika** [cossou/JasperPHP#33]
If you have some time to replay to me. 
I try to use JasperPHP in Laravel 5 but can't. I make sample report with static text:
![test report](https://cloud.githubusercontent.com/assets/10199584/13254745/085187ba-da43-11e5-863c-60f106ed2482.png)
But when I publish it and start with Laravel with that code:

        $output = public_path() . '/report/Test';
        $ext = "pdf";
        $jasper = JasperPHP::compile(
            public_path() . '/reports/Test.jasper',
            true
        )->execute();

        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename='.time().'Test.'.$ext);
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Pragma: public');
        header('Content-Length: ' . filesize($output.'.'.$ext));
        flush();
        readfile($output.'.'.$ext);
        unlink($output.'.'.$ext); // deletes the temporary file

And Laravel gives me an error:

Exception in JasperPHP.php line 178: Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.

Can you help me? What I do wrong? I would like to generate pdf file for that report and send it to client. 

Also one more question. How to send param to report?

The same problem I have when try with real report with datasets 

TNX.

**Comment by cossou** [comment]
Hi there,

You already have a .jasper so you need to use the process() function
(instead of the compile)

Check the example on the readme.
Em 24/02/2016 05:48, "Stojan Kukrika" <notifications@github.com> escreveu:

**Comment by stojankukrika** [comment]
I change it with:

        $jasper = new JasperPHP;
        $jasper->process(
            public_path() . '/reports/Faktura.jasper',
            $output,
            array("pdf"),
            array("fID"=>$request->fID),
            Config::get('database.connections.mysql')
        )->output();

Where is fID param. in report Faktura and also get error:
Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.

when try output I get that in output:
![output](https://cloud.githubusercontent.com/assets/10199584/13279918/2c2de7bc-dadb-11e5-8016-526f5e0c324f.png)

**Comment by cossou** [comment]
Try this:

$jasper = new JasperPHP;

$x = $jasper->process( public_path() . '/reports/Faktura.jasper', $output,
array("pdf"), array("fID"=>$request->fID),
Config::get('database.connections.mysql') )->output();

echo $x;

And the run the command in your terminal.
Em 24/02/2016 08:44, "Stojan Kukrika" <notifications@github.com> escreveu:

**Comment by stojankukrika** [comment]
I get in web:
jasperstarter process "C:\xampp\htdocs\managerreport\public/reports/Faktura.jasper" -o "C:\xampp\htdocs\managerreport\public/reports" -f pdf -P fID=1746392 -t mysql -u root -H 192.168.3.107 -n manager2007

Then copy that in terminal and get that:

C:\xampp\htdocs\managerreport>jasperstarter process "C:\xampp\htdocs\managerreport\public/reports/Faktura.jasper" -o "C:\xampp\htdocs\managerreport\public/reports" -f pdf -P fID=1746392 -t mysql -u root -H 192.168.3.107 -n manager2007
'jasperstarter' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cossou** [comment]
Looks like the directory of the jasperstarter is no correct. 
Can you add the `jasperstarter` to your PATH?

**Comment by stojankukrika** [comment]
Hmm ok. How find path for jasperstarter?

**Comment by cossou** [comment]
Should be inside your project in: 

vendor/cossou/jasperphp/src/jasperstarter/bin/jasperstarter.exe

-- 
Hélder

On 24 Feb 2016 at 09:41:54, Stojan Kukrika (notifications@github.com) wrote:

Hmm ok. How find path for jasperstarter?

**Comment by stojankukrika** [comment]
I hope that now I am sett it correctly. But Now I have another problem that I get in terminal: Unable to load driver: com.mysql.jdbc.Driver. Did you know how to setup it? I find mysql-connector-java-5.1.34-bin.jar here:
https://github.com/cossou/JasperPHP/tree/master/src/JasperStarter/jdbc
 But do not know how to settup :(

**Comment by cossou** [comment]
I guess the problem is that you are using windows. 
This package was not properly tested in windows. Maybe you can try to use it in a UNIX environment?

**Comment by stojankukrika** [comment]
OK. I will try latter make some linux machine.TNX for help.

**Comment by stojankukrika** [comment]
Do I add Data Adapter into folder where is reports in laravel project?

**Comment by stojankukrika** [comment]
I finally find solution:
http://stackoverflow.com/questions/35622595/unable-to-load-driver-com-mysql-jdbc-driver

Tnx for time and help!

**Comment by cossou** [comment]
Great! :+1:

**Comment by alissonalberini** [comment]
Olá Senhores. estou passando por problema similar, 
php na versão 7.1.18 ( Thread Safe);

Print do core:
![image](https://user-images.githubusercontent.com/10427367/29033402-f75c3b72-7b62-11e7-8500-f079590a6a89.png)

print output:
![image](https://user-images.githubusercontent.com/10427367/29033493-3e9b212e-7b63-11e7-8d05-2343188d8265.png)


Alguém me dá uma luz?
