### ISSUE TITLE
how to set locale in parameter

### ISSUE THREAD

**Issue by r4lly99** [cossou/JasperPHP#36]
Hi, first i want to thank for this great library , my question is how to set locale to get specific currency ?
Sorry for my newbie question .

**Comment by cossou** [comment]
Hi @r4lly99 

Use the `REPORT_LOCALE` variable.

```php
JasperPHP::process(
    base_path() . '/vendor/cossou/jasperphp/examples/hello_world.jasper',
    false,
    array("pdf", "rtf"),
    array("php_version" => phpversion(), "REPORT_LOCALE" => "en")
)->execute();
```

Regards

**Comment by r4lly99** [comment]
sorry for late response , thank you very much sir 

Regards
