### ISSUE TITLE
Problem with report generation on prod enviroment

### ISSUE THREAD

**Issue by kolbergm** [cossou/JasperPHP#37]
Hi, first of all thanks for for a JasperPHP.

I've got weird issue - on dev enviroment everything works fine and reports are generating with no problems. I moved the same changes on prod enviroment but during generating the report I am getting an error:

> throw new \Exception("Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.", 1);

I've done this  (manually command execution in console) and report was generated without any problem. I've tried to change the report (I've made the empty file), filetype (pdf, html, csv etc.) and every time when I am generating from application on prod enviroment ends with error - but execution of command manually in console ends with success.

**Comment by kolbergm** [comment]
I've made some test and noticed that php exec returns 126 code, which means "Command invoked cannot execute" (Permission problem or command is not an executable). I've changed permissions for jasperstarter file (cossou/jasperphp/src/JasperStarter/bin) and now it's ok - which user should have permission to execute jasperstarter file (I've set 777, and I'm wondering if it's appropriate value)?

**Comment by cossou** [comment]
Hi @kolbergm strange problem. Never run into that before. I guess 777 is ok.
