### ISSUE TITLE
Error when move to different Centos

### ISSUE THREAD

**Issue by r4lly99** [cossou/JasperPHP#38]
Hii cossou, i have another problems now, my previous Centos 5.11 , using  java 1.6 32 bit running fine using laravel 5 with jasperphp. Now we have to move to different centos using centos 6.7 64 bit and java 1.7 64 bit. Everything already prepared and same as previous box in configuration. But now i have error 

`Exception in JasperPHP.php line 178: Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.`  

and the output after echo it

`/var/www/html/serpo/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter process /var/www/html/serpo/public/reports/monitoring.jasper -o /var/www/html/serpo/public/reports/1460347485_monitoring -f xlsx -r /var/www/html/serpo/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P REPORT_LOCALE=id_ID -t mysql -u root -p gsp -H localhost -n serpogsp`

any help will be appreciated , 
thanks

**Comment by cossou** [comment]
Hi @r4lly99 

please run the output command directly in the console and see the output.

**Comment by r4lly99** [comment]
sorry for late response sir, the output first 
`-bash: /var/www/html/sanestri/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: Permission denied
`
then i make chmod +x jasperstarter then chmod 777 jasperstarter , and next error was 
`Unable to connect to database: Communications link failure
`

**Comment by r4lly99** [comment]
sorry finally found it, my mistake on configuration mysql / hostname.
