### ISSUE TITLE
Permission denied CentOS

### ISSUE THREAD

**Issue by jaysongyn** [cossou/JasperPHP#39]
When I try to run my program on CentOS I'm getting this error bellow, when I run my code on windows is working perfectly. Am I missing anything ?

array(6) { [0]=> string(134) "OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fb28405e000, 2555904, 1) failed; error='Permission denied' (errno=13)" [1]=> string(1) "#" [2]=> string(76) "# There is insufficient memory for the Java Runtime Environment to continue." [3]=> string(100) "# Native memory allocation (malloc) failed to allocate 2555904 bytes for committing reserved memory." [4]=> string(57) "# An error report file with more information is saved as:" [5]=> string(28) "# /tmp/jvm-9854/hs_error.log" }

**Comment by cossou** [comment]
Hi @jaysongyn,

I guess 

> There is insufficient memory for the Java Runtime Environment to continue.

says it all. 😄

**Comment by jaysongyn** [comment]
But when I try to execute the command from terminal is working.

**Comment by cossou** [comment]
Maybe the sum of ```PHP``` + ```JRE``` is too much. 
Try a empty PHP file with: 
```php
<?php exec($THE_COMMAND); 
```

**Comment by jaysongyn** [comment]
I solved my problem. 

Apache doesn't have permission to execute from any folder even you set permission 777. CentOS has SElinux that manager permission by service. Apache by default only have permission to execute code from cgi-bin folder, if you want to run jasperstart from other folder you have to set permission on SElinux to execute. To test my software I disable SElinux "setenforce 0", but the good practice to solve this problem is give permission for apache. 

https://drupalwatchdog.com/volume-2/issue-2/using-apache-and-selinux-together

**Comment by cossou** [comment]
Great @jaysongyn! 👍

**Comment by gwontaeyong** [comment]
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fcc71b37000, 2555904, 1) failed; error='Permission denied' (errno=13), refer

i got a same problem with you jaysongyn
but i'm aleady setup the  httpd.conf for using cgi
how to solve the problem??

**Comment by jaysongyn** [comment]
@gwontaeyong I disabled SElinux "setenforce 0".
