### ISSUE TITLE
Getting error when adding database to jaspersoft process

### ISSUE THREAD

**Issue by eshwarallaka** [cossou/JasperPHP#41]
I'm getting following error when i use database in JasperPHP::process.
 
**Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.**

following is my code

 $jasper = new JasperPHP;
                $jasper->compile(base_path() . '/vendor/cossou/jasperphp/examples/test.jrxml')->execute();
                $jasper->process(
               base_path() . '/vendor/cossou/jasperphp/examples/test.jasper',
                array("pdf", "rtf"),
               array("php_version" => phpversion()),
               array(
               'driver' => 'pgsql',
               'username' => 'postgres',
               'host' => 'localhost',
               'database' => 'test_db',
               'password' => 'test',
               'port' => '5432',
               )
               )->execute();

if I remove array regarding database connection it successfully generate the pdf and rtf files.
NOTE:- The test.jasper file doesn't contain any data regarding database it's just a hello world text in it.

**Comment by cossou** [comment]
Hi, 

Check this https://github.com/cossou/JasperPHP/blob/master/README.md#postgresql

**Comment by urstrulyvenki** [comment]
Hi

I had the same issue..I have tried the above link code. Also I have used both mysql and postgres but still same issue..

**Comment by cossou** [comment]
Hi,

Did you run the command manually in your console with the output from the "output();" function?

**Comment by urstrulyvenki** [comment]
we have printed the output in the browser but we didn't run the command in console.Can you please let me know how can we run in console?
Here is the output we got in browser when echo

E:^^^\xampp^^^\htdocs^^^\pms^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../JasperStarter/bin/jasperstarter process E:^^^\xampp^^^\htdocs^^^\pms^^^\public/test.jasper -o E:^^^\xampp^^^\htdocs^^^\pms^^^\public/report/1465018677_codelution -f pdf -r E:^^^\xampp^^^\htdocs^^^\pms^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../../../../../ -t pgsql -u postgres -p mypwd -H localhost -n my_db

**Comment by cossou** [comment]
Change your pgsql to postgres in the driver.

**Comment by cossou** [comment]
In the readme:

Note: Laravel uses pgsql driver name instead of postgres.

**Comment by urstrulyvenki** [comment]
We have already tried that.but still same..

**Comment by cossou** [comment]
Open you command line and paste the command output. I guess it's not fully compatible with Windows environment.

**Comment by jere73** [comment]
Hello! I have the same problem, but with MySQL and Laravel. I can generate the report without parameters of database, but when I put them, the error appears.

**Comment by UnderWeb** [comment]
Me 2:

Exception in thread "main" java.lang.NullPointerException
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:138)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:551)
        at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:393)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:91)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:456)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:863)
        at de.cenote.jasperstarter.Report.fill(Report.java:248)
        at de.cenote.jasperstarter.App.processReport(App.java:217)
        at de.cenote.jasperstarter.App.main(App.java:102)

**Comment by alissonalberini** [comment]
@UnderWeb voçê conseguiu resolver o problema citado?
Estou com problema similar:

![image](https://user-images.githubusercontent.com/10427367/48275787-23c78000-e425-11e8-8a0b-6dd0c6aaa6f7.png)

A diferença é: o problema ocorre apenas em um dos ambientes de desenvolvimento onde a existência do java sdk é conflitante existe o java com versões/releases especificas para outros sistemas, não podendo assim, eu simplemtente removê-lo reinstalando na versão adequada.

![image](https://user-images.githubusercontent.com/10427367/48275902-77d26480-e425-11e8-8e97-d0abf33b9168.png)
