### ISSUE TITLE
Collection and Array parameter

### ISSUE THREAD

**Issue by LMoota** [cossou/JasperPHP#43]
I'm trying to pass as a given parameter of type array and my parameter is an ArrayList, also tried as collectible.
In CMD always says:
Parameter of type "java.util.Collection" with value x is not supported.
I tried several possible ways.
Can anyone help me?

**Comment by cossou** [comment]
Hi @LMoota

No idea how you can archive that. Try contacting jasperstarter project and see if they support that.

**Comment by LMoota** [comment]
Pass me the address of the project, please.
