### ISSUE TITLE
Problems with parameter

### ISSUE THREAD

**Issue by KNIGHTMASTER** [cossou/JasperPHP#44]
I'm trying to pass parameter from HTML form into JasperPHP. But, i don't know where to put those parameters into JasperPHP.
Here is my snippet:
$this->jasperPHP->process(
            $this->getSourceReport(), 
            $this->output,
            array($this->choosenExt),
            array(),
            $this->configurationDatabase,
            false,
            false
        )->execute();

Can anyone help me ?

**Comment by LMoota** [comment]
$this->jasperPHP->process(
$this->getSourceReport(), 
$this->output,
array(**'NAME_PARAMETER'**=>$this->choosenExt),
array(),
$this->configurationDatabase,
false,
false
)->execute();


should not contain the name of the parameter ?

**Comment by cossou** [comment]
Why don't you read the MANUAL? 

```php
JasperPHP::process(
    base_path() . '/vendor/cossou/jasperphp/examples/hello_world.jasper',
    false,
    array("pdf", "rtf"),
    array( // HERE IS A "key => value" ARRAY!
         "php_version" => phpversion(), // first parameter
         "second" => 'xxx' // you can add second parameter like this
    ),
    array(
      'driver' => 'postgres',
      'username' => 'vagrant',
      'host' => 'localhost',
      'database' => 'samples',
      'port' => '5433',
    )
  )->execute();
```
