### ISSUE TITLE
Problem migrating reports done in windows for laravel 5.2 to ubuntu

### ISSUE THREAD

**Issue by Cardozo17** [cossou/JasperPHP#46]
Hi, the problem I am having is I made my whole system on windows and now my reports works great, now I am deploying my project in ubuntu in a apache2 server but I am having problems with the reports. When I try to run a report I am getting this error:

Exception in JasperPHP.php line 178: Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.

When I get the output I'm obtaining this: 

JasperPHP {#205 ▼
  #executable: "/../JasperStarter/bin/jasperstarter"
  #the_command: "/var/www/html/StudInfSystVicDav/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter process /var/www/html/StudInfSystVicDav/public/reportJasperVD/citacion.jasper -o /var/www/html/StudInfSystVicDav/public1467063949_citation -f pdf -r /var/www/html/StudInfSystVicDav/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P parameterDocumentId=V20847147 realPath=/var/www/html/StudInfSystVicDav/public/images/ -t mysql -u root -p chelsea17 -H localhost -n vicentedavila"
  #redirect_output: false
  #background: false
  #windows: false
  #formats: array:13 [▶]
  #resource_directory: "/var/www/html/StudInfSystVicDav/vendor/cossou/jasperphp/src/JasperPHP/../../../../../"
}

If I run the_command in the console it runs fine and I get no mistakes. Before I was getting this mistake:  bash: var/www/html/StudInfSystVicDav/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: /bin/sh^M: bad interpreter: No such file or directory

What I did was applying this command again composer require cossou/jasperphp

After that I stop getting this error:  bash: var/www/html/StudInfSystVicDav/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: /bin/sh^M: bad interpreter: No such file or directory
when I put the_command in console but the report isn't working anyway. 

I am the same guy from twitter. Please help me :S I am stuck with this. Thank you

**Comment by Cardozo17** [comment]
Update:  When I put the the_command on console I am getting the correct pdf in my project folder I had not noticed that before. But It's crashing to display it in the browser. Any idea what the problem is?

**Comment by cossou** [comment]
Maybe it's a permission from your Apache user. Check if your installation allows you to execute commands in php.

**Comment by Cardozo17** [comment]
It was a permissions issue I just granted all privilegies to the folders in the project and it worked. i have to see which folders do I need to give special permissions exactly so I could keep the system safe.

**Comment by AnGuisi** [comment]
I am having the following problem in Windows 7 64bit.

D:^^^\projects^^^\rrhh-panama^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../JasperStarter/bin/jasperstarter process D:^^^\projects^^^\rrhh-panama^^^\public/reports/Nomina.jasper -o D:^^^\projects^^^\rrhh-panama^^^\public/reports/Nomina -f pdf -r D:^^^\projects^^^\rrhh-panama^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../../../../../ -P nomina_id=1 -t mysql -u root -H 127.0.0.1 -n rrhh-panama --db-port 3306
bash: D:^^^projects^^^rrhh-panama^^^vendor^^^cossou^^^jasperphp^^^src^^^JasperPHP/../**JasperStarter/bin/jasperstarter: No such file or directory**

Any solution?
