### ISSUE TITLE
list_parameters needs redirect

### ISSUE THREAD

**Issue by lordemanonsr** [cossou/JasperPHP#47]
If using the same instantiated class, list_parameters fails if done after a compile.

The $redirect_output flag is set to TRUE for the compile and remains true for the list_parameters which results in no parameter output.

The list_parameters method definition needs to be changed to:
public function list_parameters($input_file, $redirect_output=false)

then add

$this->redirect_out = $redirect_out;

before the function return call.

**Comment by cossou** [comment]
Hi @lordemanonsr thanks for reporting it. Mind doing a PR?

**Comment by lordemanonsr** [comment]
Sorry but that was so long ago and I don't even have the code base any more. I grabbed it to try and use it for a project. Reported that problem but found that Jasper wouldn't be able to do what I needed so I dumped the code. So I don't even have what I fixed any more.

**Comment by cossou** [comment]
Thanks
