### ISSUE TITLE
Laravel 5 sample

### ISSUE THREAD

**Issue by ddmo** [cossou/JasperPHP#49]
Hi, I'm newbie of Jasper Report. I've installed JasperPHP and downloaded Jaspersoft studio.
Where I can find a tutorial? I don't know how to start...
Thanks

**Comment by cossou** [comment]
Hi,

Check this https://gist.github.com/cossou/8369900 for L4. Should work fine for L5.

**Comment by ddmo** [comment]
I've tried. I've create a report file in the jaspersoft studio workspace. The report preview works fine. I've copied the jrxml and jasper file to app/storage/report folder.
The problem is that I receive any error and any output.
This the code:

`	    $jasper = new JasperPHP;

	    // Compile a JRXML to Jasper
	    $jasper->compile(storage_path() . '/report/test.jrxml')->execute();

	    // Process a Jasper file to PDF and RTF (you can use directly the .jrxml)
	    $jasper->process(
	        storage_path() . '/report/test.jasper',
	        storage_path() . '/report/test',
	        array("pdf"),
	        array("php_version" => phpversion()),
	        Config::get('database.connections.mysql') //DB connection array
	    )->execute();

`
Which is the problem?
Thanks a lot
Stefano

**Comment by ddmo** [comment]
Ok, I've change from array("php_version" => phpversion()) to array() and works fine.
Thanks
