### ISSUE TITLE
can i show html element in my report?

### ISSUE THREAD

**Issue by ferrysutanto19** [cossou/JasperPHP#5]
guys,

i want to know if i could show an html element in my report?
i'm using jasper studio to design my report jrxml,
if i only use a static field, then i compile and process using cossou/jasperphp, it would show.
but the problem came when i put an html element there, my app just returned an error like this
"There was and error executing the report! Time to check the logs!".
i've been wondering if something wrong with my jrxml, but then again when i try to preview in jasper studio it would run fine.

and here's my environment :
- latest jasper studio as of now (the time i write this)
- latest cossou/jasperphp using composer
- latest laravel 4 release

sorry if it's something stupid, i'm new to PHP and laravel, i've tried to search about this but didn't found anything, maybe it's a mistake on my part, i ask for your tolerance in advance. Thanks.

**Comment by cossou** [comment]
Hi @ferrysutanto19 

I somehow missed your issue and just saw it now. 
Try to get the command output from the JasperPHP and execute it in your shell manually. That way you can see the actual output from the error.
