### ISSUE TITLE
Error with order field

### ISSUE THREAD

**Issue by ddmo** [cossou/JasperPHP#50]
Hi, I've a query like this one:

```
select * from table
order by $P!{orderField}

```
If I run a preview in Jaspersoft Studio with value "ordercolumn ASC" instead of orderField parameter, works fine.

With JasperPHP with array("orderField" => "ordercolumn ASC") fails with "Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console."

Without direction statement works fine (array("orderField" => "ordercolumn")).

Any suggestion?
Thanks
Stefano

**Comment by cossou** [comment]
Hi!

Check the output from the console. It should show the problem with the report.

**Comment by ddmo** [comment]
Ok, can you show me how?
Thanks
Stefano

**Comment by ddmo** [comment]
Ok, resolved. Double quotes problem.
Thanks
