### ISSUE TITLE
escapeshellcmd 

### ISSUE THREAD

**Issue by claudiogg88** [cossou/JasperPHP#51]
in windows the function escapeshellcmd  make the command bad escape paths. adding "^^^" unnecesary.

example: \vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/.

command return "file not found" when im run manually.

its this a bug?

thanks

**Comment by cossou** [comment]
Hi @claudiogg88 

I don't currently have a windows machine to test this out. 
Did you figure it out?

**Comment by claudiogg88** [comment]
my error. sorry.
