### ISSUE TITLE
Problems using lists()

### ISSUE THREAD

**Issue by atsoares** [cossou/JasperPHP#52]
I've seen some examples of how to use the package but the way that I need to use isn't working.

First, I tried to use the method all() and as it returns a collection of objects was necessary to use a foreach(), but I got this problem as answer:

 PHP error:  Array to string conversion in /home/vagrant/Projetos/sgp-web/vendor/lavela/phpjasper/src/JasperPHP/JasperPHP.php on line 102

It works when I get just one value from the array, but that is not what I want (just saying that I know how to do when I get the parameters from an input as an example). 

Then, asking for help in another forum someone said that I should try to use lists(), but doing so I've got this: 

Wrong report param format! NUMERO
Exception with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.'

Can you help me Cossou?

**Comment by atsoares** [comment]
Here is the code:

        $nomeCompleto = $this->PessoaRepository->lists('nome_completo');
        $cpf = $this->PessoaRepository->lists('cpf');

        $jasper = new JasperPHP();

        // Process a Jasper file to PDF and RTF (you can use directly the .jrxml)
        $jasper->process(
            app_path() . "/Domains/Pessoas/Reports/Pessoa/listaPessoas.jrxml",
            false,
            array('pdf', 'rtf', 'xls', 'xlsx', 'docx', 'odt', 'ods', 'pptx', 'csv', 'html', 'xhtml', 'xml', 'jrprint'),
            array("nomeCompleto" => $nomeCompleto,
                "cpf" => $cpf),
            array(
                'driver' => 'postgres',
                'username' => 'homestead',
                'password' => 'secret',
                'host' => '127.0.0.1',
                'database' => 'sgpweb',
                'port' => '5432',
            )
        )->execute();

PS: using the method dd(), I've checked that $cpf returns me this:

Illuminate\Support\Collection {#831
  #items: array:3 [
    1 => "05906098313"
    2 => "57632395393"
    3 => "09590625800"
  ]
}

**Comment by cossou** [comment]
Hi @atsoares 

you cannot pass Arrays to Jasper. 
Jasper only accepts Strings or Integers.

Think about passing a ID to Jasper and then retrieve the CPFs from the Database.

Regards,
Hélder

**Comment by atsoares** [comment]
How can I do it?

Is there any example?

**Comment by cossou** [comment]
Sorry, I can't give you an example. 

Think about using the database to fetch the values you need in the report.

**Comment by shawe** [comment]
@cossou can work if array is converted to json?

I'm interested on create a table dinnamically from an array, without now the exact quantity of cols and rows.
