### ISSUE TITLE
Doesn't render a chart

### ISSUE THREAD

**Issue by lr12003** [cossou/JasperPHP#53]
Hi! I am working with Ireport 5.0.1 and postgres, well I created a gantt diagram using JFreeChart available in Ireport, so when I load the report, it throws a error, does JasperPHP support charts?

**Comment by cossou** [comment]
Hi @lr12003 

It should work fine. 

Can you run the command in your terminal and check the output?

**Comment by lr12003** [comment]
Great cossou! I ran the command: jasperstarter pr myreport .jrxml -f view,  and I could see the error, I got a error with the theme of chart in this case gantt diagram, the advice is set "default" theme to chart, so avoid problems. Thanks so much! your work is excellent!
