### ISSUE TITLE
(not quite an issue ...) how hard would it be to hav webservice as datasource

### ISSUE THREAD

**Issue by ruiisidro** [cossou/JasperPHP#54]
I'm using a rest datasource and would like to understand how hard would it be to add  the web-service-data-source (http://community.jaspersoft.com/project/web-service-data-source) as one of the available datasources.

**Comment by cossou** [comment]
Hi @ruiisidro 

sorry for the late reply.
I took a look at it seems a great approach.

I currently don't have the time to add support for webservices. 
You are welcomed to PR.


Thanks
