### ISSUE TITLE
Can't render report with mysql database connector

### ISSUE THREAD

**Issue by nicoyamin** [cossou/JasperPHP#57]
Hi cossou. First off, i wanted to thank you for such an amazing library. Today seems like the downright choice to generate php reports. 

Now, let's get to the issue: I am unable to generate a report (right now i'm just trying to render your "hello world" example) with a mysql db connection in localhost. I have tried everything, from using a generic connection string to changing the path of the provided mysql connector. Right now, my code looks like this:

``` php
    $jasper = new JasperPHP;

        $database = [
            'driver' => 'mysql',
            'username' => 'homestead',
            'password'=> 'secret',
            'host' => '127.0.0.1',
            'database'=>'VIVA',
            'port' => '33060'

        ];

    dump($database);

    $jasper->process(
    'reports/hello_world.jasper',
    false,
    array("pdf", "rtf"),
    array("php_version" => phpversion()),
    $database
    )->execute();

    exec($jasper->output().' 2>&1', $output);
    dump($output);


```

When this code is executed, it results in the following output (i dumped it to make it more readable, notice the strange input field added):

![error_output](https://cloud.githubusercontent.com/assets/1058798/20042617/228bd0f2-a45c-11e6-9730-793b93a88e44.png)

And of course, no pdf renderer in the reports folder. 

I'm using laravel homestead, and reports are generated just fine without attempting to connect to a database (meaning, with parameters only). So, dou yu have any idea of what's going on?

Thanks in advance!

**Comment by cossou** [comment]
Hi @nicoyamin 

Try this:

```php
        $jasper = new JasperPHP;

        $database = [
            'driver' => 'mysql',
            'username' => 'homestead',
            'password'=> 'secret',
            'host' => '127.0.0.1',
            'database'=>'VIVA',
            'port' => '33060'
        ];

    $output = $jasper->process(
    'reports/hello_world.jasper',
    false,
    array("pdf", "rtf"),
    array("php_version" => phpversion()),
    $database
    )->output();

    echo $output;
```

**Comment by nicoyamin** [comment]
Hi, thanks for the repsonse!

The output is as follows:

```
/home/vagrant/Code/viva/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter` process reports/hello_world.jasper -f pdf rtf -r /home/vagrant/Code/viva/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P php_version="7.0.8-2+deb.sury.org\\\~xenial+1" -t mysql -u homestead -p secret -H 127.0.0.1 -n VIVA --db-port 33060
```
Everything looks in order: we got driver, user, password, host, db name and port specified. Maybe it has something to do with that path "src/JasperPHP/../../../../../"?

In the meanwhile, i'm tinkering with jasperstarter, trying to get a working command to achieve the connection, so i can compare it whit this output and locate the issue. If you have any ideas, please let me know.

Thank you for your help

**Comment by cossou** [comment]
Copy and paste the output to your console and execute it. Let me know the result. I see that there is a ` in your code after jasperstarter. Is that an error?

**Comment by nicoyamin** [comment]
Ok, starting from the folder of your library where you provided jasperstarter, i execute the output:
```
jasperstarter process hello_world.jasper -f pdf rtf -r /home/vagrant/Code/viva/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P php_version="7.0.8-2+deb.sury.org\\\~xenial+1" -t mysql -u homestead -p secret -H 127.0.0.1 -n VIVA --db-port 33060
```

result: 
![cmd-jsout](https://cloud.githubusercontent.com/assets/1058798/20061167/758a3466-a4dd-11e6-8e9d-dc529939002f.png)

Oh, and that ` was a typo, so nevermind it.

It seems the driver is the conflicting point. Do i have to put it somewhere specific? I tried of course leaving it where you initially provided it (JasperStarter/jdbc folder). Also, i tried replacing it with a newer version (6.0.5) and pasting both of them (version 5.1.34 and 6.0.5 ) in the same folder as the reports files, but nothing seems to work.

Actually, i came to the same impasse when trying to generate the report using only the jasperstarter console. Will keep trying and let you know if anything changes. In the meantime, if you come up with any advice, it would be great.

Greetings

**Comment by cossou** [comment]
Strange, I see you are using vagrant, can you run that command locally in the VM? Check if you have all the requirements (README.md).

**Comment by nicoyamin** [comment]
Ok, cossou, I tried running the command locally. Without a connection string, all goes well:
![cmd-vagrantok](https://cloud.githubusercontent.com/assets/1058798/20068248/b9624c6e-a4f6-11e6-90f1-6c2f99e2efc6.png)

But when I add the mysql jdbc factor, this is the output:

![cmd-vagrantfail](https://cloud.githubusercontent.com/assets/1058798/20068325/0dbd7dd8-a4f7-11e6-834e-6519af5c1d18.png)

My guess is that the jdbc is giving troubles. I'm currently looking for help on connecting to a mysql server inside vagrant VM via jdbc, so i'll update if i find something.

**Comment by cossou** [comment]
Cool! 

Let me know if you find something.

Closing it for now.

**Comment by nicoyamin** [comment]
Ok, finally found a solution.

There is one thing in common in problems like this: the lack of a complete or at least deep understanding in the technologies involved. Since i'm fairlly new in this VM development paradigm, i was a victim of this situiation. The solution couldn't be simpler:

i was using port 33060 to send the connection request. It turns out that this specific port ios provided by homestead laravel as the default port for the mysql connection inside the VM. So either it was already taken, or it wasn't recognized by the JDBC, thus resulting in a access restriction. 

**Simply using 3306 as the connection port for the JDBC and following this guide [(https://www.cyberciti.biz/tips/how-do-i-enable-remote-access-to-mysql-database-server.html)] (which i'm not sure was really a part of the solution, but trying never hurts ) did the trick.** Finally, I was able to generate a custom report and fill the info iterating from records in my DB.

So there's that. You can facepalm before my incompetence (i already did), but it is solved now, and perhaps it will help someone else.

Again thanks for your help and please keep supporting this amazing library.
