### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by erick-chali** [cossou/JasperPHP#58]
Hello I'm trying to use this library on a project on laravel 5.3, I already: 
- Installed JasperStarter
- Set the JasperStarter environment variable
- Tried to compile the .jrxml via cmd and via console it worked.

my code to output the error compiling the hello_world.jrxml example:
```
$jasper = new JasperPHP;
exec($jasper->compile(storage_path('report_templates/hello_world.jrxml'))->output().' 2>&1', $output);
print_r($output);
```

**Comment by cossou** [comment]
Hi,

Can you show the output? Is the error coming from PHP or Java?

**Comment by erick-chali** [comment]
![screenshot 175](https://cloud.githubusercontent.com/assets/6502472/20501924/7b502f2a-b001-11e6-8889-9afc7eae5240.png)


this is the output from the previous lines

**Comment by cossou** [comment]
Just from the output() function without exec function.

**Comment by erick-chali** [comment]
![screenshot 176](https://cloud.githubusercontent.com/assets/6502472/20502187/9c09f740-b002-11e6-9ff3-f9b00254b65c.png)

**Comment by cossou** [comment]
$jasper = new JasperPHP;
$jasper->process(
storage_path('report_templates/hello_world.jrxml,
    false,
    array("pdf", "rtf"),
    array("php_version" => phpversion())
->output();

**Comment by erick-chali** [comment]
A blank page
In the developer tools on chrome 
Response 200

**Comment by cossou** [comment]
Forgot to tell you to output. Do a print_r or echo of the last command.

**Comment by erick-chali** [comment]
![screenshot 177](https://cloud.githubusercontent.com/assets/6502472/20502883/becf0bf0-b005-11e6-945b-6277d4981193.png)

**Comment by cossou** [comment]
@erick-chali did you manage to fix it?

**Comment by erick-chali** [comment]
No :(

**Comment by kumaravel011** [comment]
Check whether you installed jdk (java) in your machine
