### ISSUE TITLE
Problem printing in dot matrix printer

### ISSUE THREAD

**Issue by rjose31** [cossou/JasperPHP#59]
Hi cossou,
I have tried to print in a dot matrix printer but isn't working correctly, I have used the same report in a LX-300 and work perfectly, but in the Samsung Bixolon is not correct.

I try to to change the font but with the same result, finally I change the format to 'print'(I added the format to the array format in JasperPhp)  instead 'pdf' and work perfectly only if I run the command directly from command prompt(I use windows), when I run the command from laravel the report is printed clearly but incomplete.

This is my code in Laravel:
`  $jasper->process(
    $input,
    $output,
    array($ext),
    array("php_version" => "xxx",'nfactura'=>$numero),
    $database
    )->execute();`
And this is my command from command prompt (this work perfectly):
`C:\xampp\htdocs\ContSoft\vendor\cossou\jasperphp\src\JasperPHP/../JasperStarter/bin/jasperstarter process C:\xampp\htdocs\ContSoft\public//reports//facturalce.jrxml -o C:\\xampp\\htdocs\\ContSoft\\public//reports//1480632479_factura -f print -r C:\xampp\htdocs\ContSoft\vendor\cossou\jasperphp\src\JasperPHP/../../../../../ -P php_version=xxx nfactura=FAC-00019925 -t generic -u user -p password --db-driver com.microsoft.sqlserver.jdbc.SQLServerDriver --db-url jdbc:sqlserver://localhost\MYINSTANC;databaseName=my-db`

I don't know what I'm doing wrong.

**Comment by cossou** [comment]
Hi @rjose31 sorry,

I missed your issue. Did you manage to fix it? 
Guess is a problem with Windows?
