### ISSUE TITLE
No output file created

### ISSUE THREAD

**Issue by jibelicious** [cossou/JasperPHP#6]
Hi, I'm having an issue where there is no file created.

I've tried the hello_world example, and that outputs a file, however, when i create my own file there is no file created, but i get no errors, i created a blank A4 page with just one static text field in it.

I'm using jasper studio, but from what i understand that should not be a problem, right?

Using Laravel 4.2
Latest JasperPHP via composer
Using Homestead

Route::get('test', function(){
	JasperPHP::process(
		base_path() . '/vendor/cossou/jasperphp/examples/test.jasper', 
		false, 
		array("pdf", "rtf"), 
		array("php_version" => phpversion())
	)->execute();
});

I'm sure i'm missing something here, but i cant figure out what :/

**Comment by cossou** [comment]
I guess blank file means an error creating the report. Try to output the command before it gets executed and run it by hand

**Comment by jibelicious** [comment]
Sorry, i might have been a bit unclear, there is no file being created. I created a blank (except for one static text field) .jasper file for testing... But i will try that, thanks

**Comment by RushabhBadani1991** [comment]
I tried the same, but my report shoes Null on data field... Did u get it working @jibelicious

**Comment by shresthaankit7** [comment]
is there any solution for this ??? have any one figured it out ??
