### ISSUE TITLE
jasperstarter command not working on ubuntu/linux

### ISSUE THREAD

**Issue by shriganeshbiz** [cossou/JasperPHP#61]
Good Morning cossou,
I am facing problem to run report in web server. 
Locally working fine on windows but not working on server as server is ubuntu/linux.
My local m/c is widows but server m/c is ubuntu.
I am working with laravel 5.1

Below is command i print it in the web server.
**Command :**
/var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter compile /var/www/html/mphase2nuim1/public/static/attachments/examples/hello_world.jrxml > /dev/null 2>&1 &

**Command output :**
$ /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter compile /var/www/html/mphase2nuim1/public/static/attachments/examples/hello_world.jrxml > /dev/null 2>&1 &
[1] 23322
$ 

But I am not getting any output and hello_world.jasper file not getting created

Then i tried below cmds and says **jasperstarter: command not found**

**A.) checking jasperstarter -h**

$ /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter
-bash: /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: Permission denied
$ sudo /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter
sudo: /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: command not found
$

**A.) checking directly jasperstarter -h**

$ /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperStarter/bin/jasperstarter
-bash: /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperStarter/bin/jasperstarter: Permission denied
$ sudo /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperStarter/bin/jasperstarter
sudo: /var/www/html/mphase2nuim1/vendor/cossou/jasperphp/src/JasperStarter/bin/jasperstarter: command not found
$

**My Server System Information:**

Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

$ java -version
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
$

I have tested it locally on windows its working fine.

But not working on linux So the binaries for linux are same of different binaries required for linux?

Please suggest possible solution.
Please Help me.

**Comment by shriganeshbiz** [comment]
my test code

$jasper = new JasperPHP;
$jasper->compile(base_path() . '/public/static/attachments/examples/hello_world.jrxml')->execute();

**Comment by cossou** [comment]
Hi there, try changing the permissions of the Jasper starter:

`chmod +x path/to/jasperstarter`

**Comment by shriganeshbiz** [comment]
HI cosso,

Thanks a lot.
Yes problem was permissions of the Jasper starter.
Just changing the permission it solved.
Now I am able to create pdf etc.

thanks again
