### ISSUE TITLE
Help me fix this debug

### ISSUE THREAD

**Issue by pulsenoid** [cossou/JasperPHP#62]
how to fix error like this
![index](https://cloud.githubusercontent.com/assets/5995746/23695984/5517b9e2-0414-11e7-82bc-bdaee3378dbc.jpg)

did i need setting something to use jasperPHP.
i use windows7
xampp 5.5
and user db oracle

**Comment by cossou** [comment]
Hi @pulsenoid 

sorry, cannot help you with this problem looks like it's "**Unable to connect to database**".

Thanks
