### ISSUE TITLE
Report Language Issue

### ISSUE THREAD

**Issue by muhammadatallah** [cossou/JasperPHP#63]
Thanks for this Awesome API , in fact i develop an application in Arabic language so i need to render all reports in Arabic language but unfortunately when i write one character in Arabic not render in my output 
**Empty Place** 

**Could you help me ?** 

OS => Ubuntu 16.4
Php version => 7.0
Laravel version => 5.3

Thanks

**Comment by cossou** [comment]
Hi @3a6ala 

Can you compile your report with Jasper Studio?

There is a parameter in JasperStarter called `REPORT_LOCALE` which you can pass the locale of report:
>  --locale <lang> set locale  with  two-letter  ISO-639  code  or  a combination of ISO-639 and ISO-3166 like de_DE

Example: 

```
JasperPHP::process(
    $template,
    $save_path,
    array("pdf"),
    array("something" => $id, "REPORT_LOCALE" => 'en_GB'),
    Config::get('database.connections.mysql'),
    false,
    false
)->execute();
```

Could also be related with the Font support. Not sure. 

Let me know how it goes.

**Comment by poetraRR** [comment]
hello how to use indonesian language for the date and month?
I try change the locale to ID still not working
thanks

**Comment by cossou** [comment]
Hello @poetraRR 

I belive you should use `in_ID`.

Something like:

```
JasperPHP::process(
    $template,
    $save_path,
    array("pdf"),
    array("something" => $id, "REPORT_LOCALE" => 'in_ID'),
    Config::get('database.connections.mysql'),
    false,
    false
)->execute();
```
