### ISSUE TITLE
String parameters no longer being quoted

### ISSUE THREAD

**Issue by nicoyamin** [cossou/JasperPHP#65]
Greetings cossou,

Just wanted to let you know, in a previous version of jasperphp i donwloaded, the "JasperPHP.php" file had the following piece of code:
<img width="441" alt="before" src="https://cloud.githubusercontent.com/assets/1058798/24220970/2f523242-0f2b-11e7-83ef-773798c1d903.png">

Its function was to quote string parameters, so they won't be misread by jasperstarter, i guess.

Recently i deployed a web using this library, and composer installed the current version. I couldn't generate reports and, while digging, i noticed this (in the current JasperPHP.php file):
<img width="550" alt="after" src="https://cloud.githubusercontent.com/assets/1058798/24221123/d4c6da7a-0f2b-11e7-97aa-99a423d25339.png">

So, just letting you know, because for me was a pretty hard to find error.

Was it intentional? in that case, why?

Thanks and best regards!

**Comment by cossou** [comment]
Hi @nicoyamin 

I can't find that `is_string` validation anywhere in the history.
Can you tell me the version of that piece of code?

Best regards!
