### ISSUE TITLE
JasperPhp in shared hosting

### ISSUE THREAD

**Issue by HerlyOlivares** [cossou/JasperPHP#69]
Hi cossou, 

Install JasperPHp in Laravel 5.4, and on the local server works fine, but uploading it to the hosting does not work, nor does it generate error, can generate reports in JasperPhp with a shared hosting?

**Comment by r4lly99** [comment]
maybe java not installed

**Comment by cossou** [comment]
Hi @HerlyOlivares as @r4lly99 said. Usually shared hosts don't have Java installed and also don't allow the `exec()` functions to be run.

**Comment by HerlyOlivares** [comment]
Thanks for your reply @cossou, investigating a little there, you can install an instance of Java in Cpanel, called Tomcat, here you have the link in case you can check:

Http://tomcat.apache.org/

I do not know if it works or not, and here's how to implement it in Cpanel:

Https://documentation.cpanel.net/display/EA/Introduction+to+Tomcat

Please check it and tell me if it would be possible, thanks for your help.

**Comment by cossou** [comment]
Hi @HerlyOlivares 

better check with your hosting provider.

Make sure you have both java and access to `exec()` function.


regards
