### ISSUE TITLE
Failed to execute Sample

### ISSUE THREAD

**Issue by adkarta** [cossou/JasperPHP#7]
Hi,

I'm having a trouble running your sample with current messages.
My PHP 5.5.21 (cli) on osx yosemite.

PHP Strict Standards:  Non-static method JasperPHP\JasperPHP::compile() should not be called   statically in run.php on line 6

Strict Standards: Non-static method JasperPHP\JasperPHP::compile() should not be called statically in   run.php on line 6
PHP Notice:  Undefined variable: this in JasperPHP/src/JasperPHP/JasperPHP.php on line 46

Notice: Undefined variable: this in JasperPHP/src/JasperPHP/JasperPHP.php on line 46
PHP Fatal error:  Call to a member function execute() on a non-object in JasperPHP/run.php on line 6

Fatal error: Call to a member function execute() on a non-object in JasperPHP/run.php on line 6

**Comment by cossou** [comment]
Hi @adkarta 

I think is a PHP 5.5 specific issue. 
Are you running the standard example?

**Comment by adkarta** [comment]
Hi @cossou 

Yes I just checkout your latest master and run phpunit

> Time: 35 ms, Memory: 3.00Mb
> 
> There were 2 errors:
> 
> 1) jasperphpTest::testCompileException
> Non-static method JasperPHP\JasperPHP::compile() should not be called statically, assuming $this from incompatible context
> 
> /Users/adkarta/Workspaces/personal/JasperPHP/tests/jasperphpTest.php:41
> 
> 2) jasperphpTest::testProcessException
> Non-static method JasperPHP\JasperPHP::process() should not be called statically, assuming $this from incompatible context
> 
> /Users/adkarta/Workspaces/personal/JasperPHP/tests/jasperphpTest.php:47
> 
> --
> 
> There was 1 failure:
> 
> 1) jasperphpTest::testJasperStarter
> Failed asserting that false is true.
> 
> /Users/adkarta/Workspaces/personal/JasperPHP/tests/jasperphpTest.php:33

**Comment by Marie201** [comment]
Salut.Moi aussi je peux executer l'application et la configuration!!

**Comment by efraindx** [comment]
Hi @cossou , My php version is: 5.5.12, I was trying run this code:

        JasperPHP::process(
            base_path() . '/vendor/cossou/jasperphp/examples/report1.jasper',
            false,
            array("pdf", "rtf"),
            array("php_version" => phpversion())
        )->execute();

report1.jasper is a jasper file report that I've created. The following message is shown:

Non-static method JasperPHP\JasperPHP::process() should not be called statically, assuming $this from incompatible context

Thanks in advance

**Comment by cossou** [comment]
@efraindx this is a PHP 5.5 issue. Didn't got the time to take a look.

Can you try this and see if it works:

```php 
$jp = JasperPHP::getInstance();
$jp->process(
        base_path() . '/vendor/cossou/jasperphp/examples/report1.jasper',
        false,
        array("pdf", "rtf"),
        array("php_version" => phpversion())
    )->execute()
```

Let me know if that worked.

**Comment by efraindx** [comment]
@cossou thanks for you reply, now this is shown:

call_user_func_array() expects parameter 1 to be a valid callback, class 'JasperPHP\JasperPHP' does not have a method 'getInstance'

**Comment by cossou** [comment]
@efraindx thanks. 

So I will have to take a look at this. I will try to find some time this week. If you come up with a solution let me know.

**Comment by efraindx** [comment]
Apparently you have to define a static function called: getInstance() (if you want to have a Singleton in that class). I've just tried this:

  $jp = new JasperPHP();
        $jp->process(
            base_path() . '/vendor/cossou/jasperphp/examples/report1.jasper',
            false,
            array("pdf", "rtf"),
            array("php_version" => phpversion())
        )->execute();

Apparently this work, but now a custom exception message is shown:

There was and error executing the report! Time to check the logs!

**Comment by cossou** [comment]
Nice. So that means that you have an error in your report (in the Jasper). The easiest way is to capture the command from the `$this->the_command`  https://github.com/cossou/JasperPHP/blob/master/src/JasperPHP/JasperPHP.php#L130 and run it in your terminal.

**Comment by cossou** [comment]
Let me know if that worked. For now I will just close this up!
