### ISSUE TITLE
Passing parameter containing space

### ISSUE THREAD

**Issue by bleeloe** [cossou/JasperPHP#71]
hi @cossou  do you have issue when passing parameter value containing space character?

e.g i want to pass piece of where query to parameter 
`sql_where=WHERE trdate BETWEEN '2017-06-01' AND '2017-06-03' `
i got this error 
Wrong report param format! trdate

when i wrap it with " " then jasper output would generate 
`sql_where="WHERE trdate BETWEEN \'2017-06-01\' AND \'2017-06-03\' " ` 
of course this code will generate sql error because i don't need escape string \' what i need only single quote  only '

i have extend your jasperclass to modify property $this->the_command with stripcslashes 
`
public function clean_cmd()
    {
        $this->the_command = stripcslashes($this->the_command);
        return $this;
    }
`
jasper output string still 
`sql_where="WHERE trdate BETWEEN \'2017-06-01\' AND \'2017-06-03\' " ` 
what i need is 
`sql_where="WHERE trdate BETWEEN '2017-06-01' AND '2017-06-03' " ` 

any idea?

**Comment by cossou** [comment]
Hi @bleeloe 

sorry, I think this is parsed by the `escapeshellexec` functions for security. 
The script is not ready to take parameters with quotes. I suggest you send only the dates and then build your SQL accordingly.
If you which to use the `clean_cmd` make a fork of the project and adapt it to your needs. I think is the best solution.

Regards,
Hélder
