### ISSUE TITLE
Error when run command composer update with laravel 5.4

### ISSUE THREAD

**Issue by fredroo** [cossou/JasperPHP#72]
last version of laravel 5.4.23

show this error

![image](https://user-images.githubusercontent.com/6863089/27709351-bb233422-5ce9-11e7-9474-94e7aa3e7fe3.png)

my composer.json

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "FortAwesome/Font-Awesome": "*",
        "acacha/admin-lte-template-laravel": "^4.1",
        "barryvdh/laravel-cors": "^0.8.6",
        "cossou/jasperphp": "^2.2",
        "kris/laravel-form-builder": "^1.11",
        "laravel/framework": "5.4.*",
        "laravel/passport": "^2.0",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "michael/laravelpagseguro": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.3",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}

```

**Comment by fredroo** [comment]
@cossou please check this

**Comment by cossou** [comment]
@fredroo why do you think is a problem with JasperPHP?

**Comment by fredroo** [comment]
When remove JasperPHP not show for me any errors

**Comment by cossou** [comment]
You have to debug it. I cannot help you.
It works fine on my machine with 5.4.27

<img width="455" alt="captura de ecra 2017-06-29 as 21 58 25" src="https://user-images.githubusercontent.com/1337112/27710041-2df6df2c-5d16-11e7-8b8a-45d1887ff859.png">

Good luck!

**Comment by fredroo** [comment]
@cossou  in version master solved look
in version 2.2 in cossou\jasperphp\src\JasperPHP\JasperPHPServiceProvider.php  line 18 errror

please updadte

**Comment by cossou** [comment]
Ok, just published v2.3.0 
Let me know if that fixed the issue.

Thanks

**Comment by fredroo** [comment]
Now works fine in version "2.3.0" and LARAVEL version "5.4.27"

please update readme with CENTOS/FEDORA to installl JDK 
$ sudo yum install java-1.7.0-openjdk-devel

**Comment by cossou** [comment]
Make a pull request to the readme, please.

**Comment by chliguiy** [comment]
you must change it 
   $this->app['jasperphp'] = $this->app->singleton(function()
    {
           return new JasperPHP;
     });
by it 
            $this->app->singleton('jasperphp', function () {
            return new JasperPHP;
});

**Comment by cossou** [comment]
@chliguiy check version 2.3.0. Already have it.
