### ISSUE TITLE
update file JasperPHP.php in line 98

### ISSUE THREAD

**Issue by AdnaneX** [cossou/JasperPHP#73]
can you pls update this line
`$command .= " " . $key . '=' . $value;`
to this
`$command .= " " . $key . '="' . $value .'"';`
for make set parameters easy.
thank you.

**Comment by tremusa** [comment]
if a parameter contains space character/s, the application will crash with the original line. But you set it, as AdnaneX's correction, it will not. Thanks, AdnaneX. I did it manually.

And thank you Hélder Duarte, for all of this application.

**Comment by jere73** [comment]
Hello, i have this error:
Call to undefined method JasperPHP\Facades\JasperPHP::process()
What can i do?

**Comment by valluminarias** [comment]
Why not submit PR?

**Comment by AdnaneX** [comment]
ok. thanks
