### ISSUE TITLE
Call to undefined method JasperPHP\Facades\JasperPHP::process()

### ISSUE THREAD

**Issue by jere73** [cossou/JasperPHP#76]
Hello, I have this error:
**Call to undefined method JasperPHP\Facades\JasperPHP::process()**
I put the sentence in the content providers, but is not working.
Any idea?
Thanks!

**Comment by cossou** [comment]
Hi @jere73 

I think you are not using the use in  your class  "```use JasperPHP;```".
Take a look at this: https://github.com/cossou/JasperPHP#using-laravel-5

**Comment by jere73** [comment]
Hello cossou, that problem has already been solved, thanks. My real problem is that when I add the parameters to connect to my database, it does not show the report, but if I remove them it works. I use MySQL with Laravel on windows 10 and I've been trying to make it work for 4 days. Thank you in advance for your help.

**Comment by cossou** [comment]
Great news! Good job!
