### ISSUE TITLE
Have problem to connect with sqlsrv driver

### ISSUE THREAD

**Issue by plateena** [cossou/JasperPHP#8]
i'm using laravel 4 on ubuntu server php 5.5 something.

when i run the process without $db_connection parameter with test.jrxml it run smoothly and create the file i want.

but when i add the $db_connection as example Config::get('database.connections.sqlsrv'), it stop creating file .pdf etc. there are no problen creating .jasper file.

i already add into /src/JasperStarter/jdbc the sqljdbc41.jar and even the jtds.jar

sorry for my bad english

**Comment by cossou** [comment]
Hi there, 

did you try to play with the Jasper Studio and SQL Server? If not, I would recommend you to try that first. 

I think the problem can be because SQL Server uses a different driver that "sqlsrv" in the JasperStarter.
 
Take a look at http://jasperstarter.sourceforge.net/usage.html and see the `-t` option.

```
db options:
  -t <dbtype>            database type: none,  csv,  xml,  mysql, postgres,
                         oracle, generic
  -H <dbhost>            database host
  -u <dbuser>            database user
  -p <dbpasswd>          database password
  -n <dbname>            database name
  --db-sid <sid>         oracle sid
  --db-port <port>       database port
  --db-driver <name>     jdbc driver class name for use with type: generic
  --db-url <jdbcUrl>     jdbc url without user, passwd with type:generic
  --jdbc-dir <dir>       directory where  jdbc  driver  jars  are  located.
                         Defaults to ./jdbc
```

 Also check these lines: https://github.com/cossou/JasperPHP/blob/master/src/JasperPHP/JasperPHP.php#L92-L102

**Comment by plateena** [comment]
Hi,

tq for quick reply.

I already play with Jasper Studio and it work well with SQL Server.  FYI it on the same server.

**Comment by adrianoleiterodrigues** [comment]
I had the same problem!
Solved as follow...

From cmd:

java -jar jasperstarter.jar pr c:\projetos\controle-cheques\reports\demonstrativooperacao.jasper -f pdf -P parameter=value -t generic -u username -p password --db-driver com.microsoft.sqlserver.jdbc.SQLServerDriver --db-url jdbc:sqlserver://YOUR\Host:1433

JasperPHP.php

        if( count($db_connection) > 0 )
        {
            $command .= " -t " . $db_connection['driver'];
            $command .= " -u " . $db_connection['username'];
    
            if( isset($db_connection['password']) && !empty($db_connection['password']) )
                $command .= " -p " . $db_connection['password'];

            if( isset($db_connection['host']) && !empty($db_connection['host']) )
                $command .= " -H " . $db_connection['host'];
            
            if( isset($db_connection['host']) && !empty($db_connection['host']) )
                $command .= " -n " . $db_connection['database'];
            
            if( isset($db_connection['jdbc_driver']) && !empty($db_connection['jdbc_driver']) )
                $command .= " --db-driver " . $db_connection['jdbc_driver'];
            
            if( isset($db_connection['jdbc_url']) && !empty($db_connection['jdbc_url']) )
                $command .= " --db-url " . $db_connection['jdbc_url'];
        }

My code:

I'm using tow databases, so I don
            $database = [
                'driver' => 'generic',
                'username' => 'username',
                'password' => 'password',
                'jdbc_driver' => 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
                'jdbc_url' => 'jdbc:sqlserver://YOUR\Host:1433'
            ];

            JasperPHP::process(
                    base_path() . '/reports/report.jasper',
                    false,
                    array("pdf"),
                    array("parameter" => "value"),
                    $database
            )->execute();

**Comment by cossou** [comment]
Thanks @adrianoleiterodrigues :+1: 
Feel free to do a PR!

**Comment by adrianoleiterodrigues** [comment]
I'm new here and I'm not that good typing in English, I hope I can have some help to do this..

**Comment by plateena** [comment]
thanks for the help @adrianoleiterodrigues...

but in my case it still generate the empty pdf...

i already tried to re-install all even add path to the jasperstarter/bin

still no luck

**Comment by plateena** [comment]
Solve the problem.

Change the driver to jtds sql and it work like charm. Maybe something wrong with sqljdbc driver.

**Comment by cossou** [comment]
:+1: Thanks!

**Comment by ferrysutanto19** [comment]
@plateena 
can you please post your code?

using your direction, i tried like this :

JasperPHP::process(
		base_path() . '/vendor/cossou/jasperphp/examples/Blank_A4.jasper',
		false,
		array("pdf", "rtf"),
		array(null),
		array(
			'driver' => 'generic',
			'username' => 'sa',
			'password' => 'password',
			'jdbc_driver' => 'net.sourceforge.jtds.jdbc.Driver',
			'jdbc_url' => 'jdbc:sqlserver://localhost:1433'
		)
	)->execute();

not working,

tried what @adrianoleiterodrigues  suggest too,

$database = [
            'driver' => 'generic',
            'username' => 'username',
            'password' => 'password',
            'jdbc_driver' => 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
            'jdbc_url' => 'jdbc:sqlserver://YOUR\Host:1433'
        ];

        JasperPHP::process(
                base_path() . '/reports/report.jasper',
                false,
                array("pdf"),
                array("parameter" => "value"),
                $database
        )->execute();

still not working, i'm wondering what's wrong with my code.

FYI i'm using laravel 5 on windows, php 5.6.

**Comment by adrianoleiterodrigues** [comment]
@ferrysutanto19 

What's the error message?
You tried to get the output code and execute in the windows cmd?

**Comment by rjosecruz** [comment]
Hi cossou, I am trying to excecute a reporte using sql server, I connected with the database but when I run from my route I got this error:

Exception in JasperPHP.php line 192: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.
I use the output() command and I get this line 

jasperstarter process "C:\xampp\htdocs\ContSoft\public/reports/factura.jrxml" -o "C:\xampp\htdocs\ContSoft\public/reports/1465278983_factura" -f pdf -P php_version="5.6.21" nfactura="FAC-00043535" -t generic -u sa -p ferrosoft --db-driver com.microsoft.sqlserver.jdbc.SQLServerDriver --db-url jdbc:sqlserver://localhost\MYM;databaseName=sys_ferrecomsa
when I run from the command line I got the report correctly, but no from the route, where is the error?

**Comment by adrianoleiterodrigues** [comment]
Hey @rjosecruz, can you post your code?

**Comment by ederivero** [comment]
Hello everybody I m trying to connect with sql server but my password is @ntenas2016 my problem is the first letter is "@" and when I execute in cmd the error is the next 

"jasperstarter: error: Could not read arguments from file 'ntenas2016'"

how I can do? Thank you

**Comment by ederivero** [comment]
Hello everybody I have a problem with my connection.
The problem is the password 
"'driver' => 'generic',
      'username' => "antenas",
	  'password' => "'@ntenas2016",
      'jdbc_driver' => 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
	  'jdbc_url' => 'jdbc:sqlserver://PROINCORP-SRV1\PROINCORP1;databaseName=ANTENAS;',"

The first letter is a character '@' so when I try to run in CMD 
![image](https://cloud.githubusercontent.com/assets/4792446/16358134/5cf6e6e6-3ad0-11e6-8eef-b767cc337e92.png)
HELP ME PLEASE

**Comment by adrianoleiterodrigues** [comment]
@ederivero
Try this: 'password' => '"@ntenas2016"',

**Comment by ederivero** [comment]
No :( the same error anymore?

**Comment by cossou** [comment]
@ederivero the problem is you are using a password (with the @ symbol) that breaks command execution. Try using a different password and see if it works.

**Comment by ederivero** [comment]
Im thinking that but is the password for the database company or is the only way?

**Comment by cossou** [comment]
Try changing the password first. 
Later we can check if we can put some `"` to escape these fields.

**Comment by ederivero** [comment]
@cossou  ok thank you im try it

**Comment by ederivero** [comment]
I solved all I had to do was create a new user and put the '@' in the middle of the password thanks for your help

**Comment by hudaazzuhri** [comment]
1. copy jtds-1.3.0.jar to /vendor/cossou/jasperphp/src/JasperStarter/jdbc
2. set connection :
   	    $connection = [
                'driver' => 'generic',
                'username' => 'username',
                'password' => 'password',                
                'jdbc_driver' => 'net.sourceforge.jtds.jdbc.Driver',
                'jdbc_url' => 'jdbc:jtds:sqlserver://localhost:1433;databaseName=database'
            ];

**Comment by smartagileAndy** [comment]
Dear sir
I have a problem
my setting
`$database = [
						'driver' => 'generic',
						'username' => 'sa',
						'password'=> '1234',
						'database'=>'AAA',
						'jdbc_driver' => 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
						'jdbc_url' => 'jdbc:sqlserver://192.168.10.1:1433'
];`

when i output the command
` /var/www/html/ts/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter process /var/www/html/ts/public_/report_/mainPage_/gpsOverSpeedNotice.jasper -o /var/www/html/ts/documents/tmp_/17446726245d5ac5ef0e4c85d5ac5ef0e4c9 -f pdf -r /var/www/html/ts/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P TRABE_NAME="AAA" TRABE_BE002="5bebbe8ab62e4" TRABE_BE100="2019-08-14" -t generic -u sa -p 1234 -n cpdc_ts --db-driver com.microsoft.sqlserver.jdbc.SQLServerDriver --db-url jdbc:sqlserver://192.168.10.1:1433
`
 i get the error code
`Error filling reportError executing SQL statement for: gpsOverSpeedNotice.`
i need advice, thank you.
