### ISSUE TITLE
Bug on v 2.4.0

### ISSUE THREAD

**Issue by rafwell** [cossou/JasperPHP#81]
Hello, after upgrade for 2.4.0 my script stop work. He is saying `Unable to load driver: com.mysql.jdbc.Driver`, i've downgraded to 2.3.0 and now work fine.

**Comment by cossou** [comment]
Thanks, I will look into it to see if I find any problem.

Em 24/11/2017 7:27 da tarde, "Rafael Souza" <notifications@github.com>
escreveu:

**Comment by cossou** [comment]
Hi @rafwell 

The problem is fixed in the new 2.5.0 version. 
The JDBC drivers were deleted from the JasperStarter/jdbc directory.

Thanks
