### ISSUE TITLE
Error commad output in Windows

### ISSUE THREAD

**Issue by nurrochim** [cossou/JasperPHP#82]
I am using Windows as server
I have an error while run simple Hello_World report
this output from JasperPHP::output
E:^^^\My Project^^^\PHP Tutorial^^^\AplikasiManajemenInsiden^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../JasperStarter/bin/jasperstarter process E:^^^\My Project^^^\PHP Tutorial^^^\AplikasiManajemenInsiden^^^\public/file_incident/hello_world.jasper -f pdf rtf -r E:^^^\My Project^^^\PHP Tutorial^^^\AplikasiManajemenInsiden^^^\vendor^^^\cossou^^^\jasperphp^^^\src^^^\JasperPHP/../../../../../ -P php_version=7.0.13

Through command promt windows, i already change thats output like : 
"E:\My Project\PHP Tutorial\AplikasiManajemenInsiden\vendor\cossou\jasperphp\src\JasperPHP/../JasperStarter/bin/jasperstarter" process "E:\My Project\PHP Tutorial\AplikasiManajemenInsiden\public/file_incident/hello_world.jasper" -f pdf rtf -r "E:\My Project\PHP Tutorial\AplikasiManajemenInsiden\vendor\cossou\jasperphp\src\JasperPHP/../../../../../" -P php_version=7.0.13
This command can generate report for sure

How to fix this command from symbol ^ to "  so can run properly in windows ?
(sory for my english grammar )

**Comment by cossou** [comment]
Hi @nurrochim thanks for the report. 

Did you found why we have ^^^ in the command path?

**Comment by nurrochim** [comment]
maybe because of escapeshellcmd()

I found a temporary solution
In JasperPHP... i change escapeshellcmd() with escapeshellarg() for every path folder, then execute again Hello_World

i don'tknow... is this the right solution or not

Thanks for @cossou for your time and response

**Comment by cossou** [comment]
Thanks for the feedback. I didn't try it in windows so it may not work properly. 

Best regards
