### ISSUE TITLE
don't create file in Cpanel

### ISSUE THREAD

**Issue by nicolasrivadeneira** [cossou/JasperPHP#83]
Hi, I run my app in CPanel, but when I execute the jasper file, nothing is created.
When i run the same app in localhost, everything is ok. I tested my app with the database in server host and it works too. 

Why the files don't be create in CPanel server?

Is there a way for download the files directly and not create in server host?

**Comment by cossou** [comment]
Hi @nicolasrivadeneira 

I believe Cpanel does not allow you to run `shell_exec` or `exec` by default.
You may need to change the configuration of your server (I have no idea how to configure it).

Best regards,
Hélder

**Comment by nicolasrivadeneira** [comment]
Thanks!
