### ISSUE TITLE
Does this support Stored Procedure calls

### ISSUE THREAD

**Issue by emperorjm** [cossou/JasperPHP#87]
My reports make requests to a Mysql database using Stored Procedure calls. When I submit all the parameters everything runs through and no errors or exceptions are given but the file does not get generated.

What could be the issue?

**Comment by cossou** [comment]
Hi there,

It should run without any problem. Check if the DB user has permissions to
do so.

Regards

Em 11/02/2018 6:04 da manhã, "Adrian Thompson" <notifications@github.com>
escreveu:

**Comment by emperorjm** [comment]
Thanks for the reply. I had to change the Language within the report query builder to "plsql".

**Comment by cossou** [comment]
Thanks for the feedback.
