### ISSUE TITLE
Java Not Found

### ISSUE THREAD

**Issue by emperorjm** [cossou/JasperPHP#89]
I have a docker container running a Laravel application and I have installed Java on the container and java -version shows that it's installed and whereis java shows that it is installed in "/usr/bin/java".

When I try to generate the report the following is returned:

 0 => "/var/www/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: 26: /var/www/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: java: not found ◀/var/www/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter: 26: /var/www/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jaspe ▶"
]

I set the JAVA_HOME varaible in "/etc/environment" and it still doesn't work.

**Comment by cossou** [comment]
Hi @emperorjm 

make sure Java is in the PATH of the web user (usually www-data).

Try running `shell_exec('java -version');` from your PHP.

Regards,
Hélder

**Comment by emperorjm** [comment]
Running `shell_exec('java -version');` returns a blank page.

**Comment by cossou** [comment]
Hope you used some print function on that.

```
<?php
$output = shell_exec('java -version');
echo "<pre>$output</pre>";
```

If you already did that you probably don't have Java installed for that user.

Try changing the exec content to this: `shell_exec('whoami');`

And compare it with the `whoami` from the command line.

**Comment by emperorjm** [comment]
`whoami` returns `www-data`. There weird thing is that `shell_exec('java -version');` returns nothing on my wondows machine running similar docker container configuration but the report generation works by installing Java on my host machine (Java is not installed within the docker container).

The problem is on the docker setup on a Linux server with `java version "1.6.0_18"` installed on the Host and `openjdk version "1.8.0_162"` within the container.

**Comment by cossou** [comment]
Strange. Afraid I cannot help you further. 
The JDK version shouldn't be a problem.

**Comment by r4lly99** [comment]
Sorry for asking, did you say running 'on window machine?', can you specify
where report will be trigger/generated

**Comment by emperorjm** [comment]
@r4lly99 I am using Docker to run my Laravel application. On my windows machine I am able to generate the reports within the Laravel application through a Form I created that submits to a controller which uses the JasperPHP library to generate the report in PDF or XLS formats. The exact docker files are used to generate the containers within a Linux machine (running Fedora Core) but the report fails.

So I captured the output of the fucntion used to generate the report (Shown in my original post) and it shows that Java is not installed.

I installed Java within the docker container and Java is also installed on the host machine but the same issue.

**Comment by cossou** [comment]
@emperorjm you must install it for the `www-data` user. 

Login to docker and then `su www-data` to change the user, then try the `java -version`.

**Comment by emperorjm** [comment]
I used the following article (https://askubuntu.com/a/702113) to be able to log into the container with the **"www-data"** user account. I used su www-data and logged in and `java -version` brought back:

`openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)`

I tried to generate the report and it still does not work. So I am not sure but I will see what else I can try later.

**Comment by cossou** [comment]
Strange. 

Capture the command  from Jasper `->output();` function instead of `->execute();`. And try to run it in the command line by hand.

**Comment by emperorjm** [comment]
I am really not sure what's happening but maybe I am missing something. The output function returned the following:

`/var/www/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter process /var/www/storage/app/reports/hello_world.jrxml -o /var/www/storage/app/public -f pdf -r /var/www/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P start_date=2018-01-01 end_date=2018-01-31 salesman_id= class_id=11 product_code= branch_code= -t mysql -u root -p team01 -H 192.168.1.4 -n refactor_debug --db-port 3306`

When I run that command within the Docker container using root and ww-data the PDF file is generated but it is blank which should not be the case. So I am missing something. This was working perfectly fine on my windows machine but I uninstalled Java on my host machine to see if it would work and now it has stopped working.

Thanks for the help guys. I am going to try to break it down piece by piece.

**Comment by emperorjm** [comment]
I found the issue. I am using Laradock's docker files (nginx, php-fpm and workspace). I was installing and configuring Java within the workspace docker container and the reason PHP could not find Java. I had to install Java within the `php-fpm` container and the reports are now being generated.

**Comment by edersoares** [comment]
@emperorjm how did you install the `Java` in `php-fpm` to run `jasperstarter`?
