### ISSUE TITLE
escapeshellcmd() 

### ISSUE THREAD

**Issue by archie20** [cossou/JasperPHP#90]
Hi,
I get this error when using the execute function. I have a base64 encoded image as a parameter to the jasper report

local.ERROR: escapeshellcmd(): Command exceeds the allowed length of 8192 bytes {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): escapeshellcmd(): Command exceeds the allowed length of 8192 bytes at ...\\vendor\\cossou\\jasperphp\\src\\JasperPHP\\JasperPHP.php:141)

**Comment by cossou** [comment]
Hi there,

I think the error is self explanatory. The base64 is too long.

Regards

A terça, 1/05/2018, 12:36, archie20 <notifications@github.com> escreveu:
