### ISSUE TITLE
Full example to trouble shoot errors

### ISSUE THREAD

**Issue by mbadaone** [cossou/JasperPHP#93]
I am new to php and jasper but i have developed jasper reports in Java. I am following your examples but i am getting errors. can you kindly give a full example on the hello world and passing data from php to the report...in java you create your list and use a bean to push data to report. 

`<?php

require_once __DIR__ . '/vendor/autoload.php'; // Autoload files using Composer autoload

use JasperPHP\JasperPHP;
JasperPHP::process(
	base_path('/vendor/cossou/jasperphp/examples/hello_world.jasper'),
	false,
	array('pdf', 'rtf'),
	array('php_version' => phpversion())
)->execute();`

error is 

> 
Fatal error: Uncaught Error: Call to undefined function base_path() in C:\xampp\htdocs\reports\index.php:7 Stack trace: #0 {main} thrown in C:\xampp\htdocs\reports\index.php on line 7

Thank you in advance

**Comment by cossou** [comment]
Hi @mbadaone 

the `base_path` is a function from Laravel Framework. 

Try running with: `__DIR__ . '/vendor/cossou/jasperphp/examples/hello_world.jasper'` instead. 

Regards,
Hélder

**Comment by cossou** [comment]
Also, you need to call it like this:

```
(new JasperPHP())->process(
    __DIR__ . '/vendor/cossou/jasperphp/examples/hello_world.jasper',
    false, 
    array('pdf', 'rtf'), 
    array('php_version' => phpversion())
)->execute();
```
