### ISSUE TITLE
pass Arabic character to report

### ISSUE THREAD

**Issue by hamzehhirzallah-minagate** [cossou/JasperPHP#97]
when I pass Arabic character as param to my report I got blank field instead of the param.. is there a way to send Arabic param?

```
 $jasper->compile(__DIR__.('/reports/test.jrxml'))->execute();
 $r = $jasper->process(
    __DIR__.('/reports/test.jasper'),
    false,
    array('pdf'),  
    array('driver_name' => 'محمد أحمد')
  )->execute();
```

**Comment by cossou** [comment]
Hi @hamzehhirzallah-minagate 

Good question. I never worked with Arabic characters. 
Try running that in the command line and see if that works.  

```
 $r = $jasper->process(
    __DIR__.('/reports/test.jasper'),
    false,
    array('pdf'),  
    array('driver_name' => 'محمد أحمد')
  )->output();

echo $r;
```

**Comment by hamzehhirzallah-minagate** [comment]
This is the output I see on screen

`/var/www/html/waybill-api/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter process /var/www/html/waybill-api/reports/test.jasper -f pdf -r /var/www/html/api/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P driver_name=`

and I see blank space in the field in pdf report

**Comment by cossou** [comment]
Try this in your terminal:
```
/var/www/html/waybill-api/vendor/cossou/jasperphp/src/JasperPHP/../JasperStarter/bin/jasperstarter process /var/www/html/waybill-api/reports/test.jasper -f pdf -r /var/www/html/api/vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P driver_name="محمد أحمد"
```

**Comment by hamzehhirzallah-minagate** [comment]
it worked !!
only if add the arabic words like you said..

**Comment by cossou** [comment]
@hamzehhirzallah-minagate try to install the latest release 2.7.0.

It should work file with string parameters.

**Comment by hamzehhirzallah-minagate** [comment]
I have upgraded to 2.7.0
but I still cant see the arabic params
`vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P driver_name=""`

but I have found that if I removed the `escapeshellcmd` in jasperPHP.php file I see the following
`vendor/cossou/jasperphp/src/JasperPHP/../../../../../ -P driver_name="محمد احمد" `

which is great, but the problem now is that from the command prompt I can generate report with Arabic successfully, **but** from the php file I still face the same problem and the param still shows blank!

any advice?

**Comment by cossou** [comment]
I don't think the problem is with `escapeshellcmd`. 
Take a look:

```
➜  ~ php -a
Interactive shell

php > $driver_name = "محمد احمد";
php > echo $driver_name;
محمد احمد
php > echo escapeshellcmd($driver_name);
محمد احمد
php >
```

**Comment by hamzehhirzallah-minagate** [comment]
with all respect but I disagree with you... the following code
$driver_name = "محمد احمد";
echo "driver Name = " . $driver_name . "<br/>";
echo "driver Name = " . escapeshellcmd($driver_name);

**Comment by hamzehhirzallah-minagate** [comment]
with all respect but I disagree with you
the following code :
```
$driver_name = "محمد احمد";
echo "driver Name = " . $driver_name . "<br/>";
echo "driver Name = " . escapeshellcmd($driver_name);
```

does not echo the same name.. it echo empty string

**Comment by cossou** [comment]
Strange. 
Which PHP version are you running? 
Mine is PHP 7.2.4 on Mac OSX 10.12.6

**Comment by cossou** [comment]
Looks like you are right. 
Although in my machine it work (not sure why).

https://3v4l.org/uCa8D

**Comment by cossou** [comment]
Hi @hamzehhirzallah-minagate I think I found the problem. 

You should install locale that supports Arabic in your machine. 
Run `locale -a` and see the output.
Look online how to install locale for Arabic and after that you should be ready to use it.

Thanks,
Hélder

**Comment by hamzehhirzallah-minagate** [comment]
Thanks
I will try it and get back to you

**Comment by hamzehhirzallah-minagate** [comment]
Hi @cossou 
I have installed the Arabic locale and here is the locale screen
```
$ locale -a
ar_JO.utf8
C
C.UTF-8
en_US.utf8
POSIX
```
I am using PHP 7.0.30, ubuntu 16.4 

I cant see the Arabic params unless I remove escapeshellcmd
but event after removing the escapeshellcmd, the params is visible in the output but not visible in the report after the execute

**Comment by hamzehhirzallah-minagate** [comment]
@cossou .. can you run any jasper report and send Arabic params on your machine?
I am thinking of using another OS and I will see if the problem is OS related or not..

**Comment by cossou** [comment]
Hi @hamzehhirzallah-minagate 
yes. The parameter works but then it does not show up in the report. 
Actually even writing Arabic labels in the report don't show up.
Guess I have to configure it to display Arabic characters and embed some fonts.

**Comment by hamzehhirzallah-minagate** [comment]
These fonts works in the report if you want to add static Arabic text
DejaVu Sans
DejaVu Serif
DejaVu Sans Mono

**Comment by cossou** [comment]
It works! 
Take a look:

[hello_world.pdf](https://github.com/cossou/JasperPHP/files/2118816/hello_world.pdf)

**Comment by hamzehhirzallah-minagate** [comment]
I have tried the hello_world.jrxml but without success
if I keep the , I get blank instead of params
and if I delete the , I get ��������� instead of the param.

can you tell me what you did to achieve the working result

**Comment by cossou** [comment]
I didn't do anything special. It's running on my Mac. 
Try to dig the Ubuntu/Java forums for some clue.
